// Code generated by go-swagger; DO NOT EDIT.

package version_standard

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// Abbestellen4Reader is a Reader for the Abbestellen4 structure.
type Abbestellen4Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *Abbestellen4Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	result := NewAbbestellen4Default(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result
}

// NewAbbestellen4Default creates a Abbestellen4Default with default headers values
func NewAbbestellen4Default(code int) *Abbestellen4Default {
	return &Abbestellen4Default{
		_statusCode: code,
	}
}

/*
Abbestellen4Default describes a response with status code -1, with default header values.

successful operation
*/
type Abbestellen4Default struct {
	_statusCode int
}

// IsSuccess returns true when this abbestellen 4 default response has a 2xx status code
func (o *Abbestellen4Default) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this abbestellen 4 default response has a 3xx status code
func (o *Abbestellen4Default) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this abbestellen 4 default response has a 4xx status code
func (o *Abbestellen4Default) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this abbestellen 4 default response has a 5xx status code
func (o *Abbestellen4Default) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this abbestellen 4 default response a status code equal to that given
func (o *Abbestellen4Default) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the abbestellen 4 default response
func (o *Abbestellen4Default) Code() int {
	return o._statusCode
}

func (o *Abbestellen4Default) Error() string {
	return fmt.Sprintf("[POST /version_standard/{urn}/abbestellen][%d] abbestellen_4 default ", o._statusCode)
}

func (o *Abbestellen4Default) String() string {
	return fmt.Sprintf("[POST /version_standard/{urn}/abbestellen][%d] abbestellen_4 default ", o._statusCode)
}

func (o *Abbestellen4Default) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
