// Code generated by go-swagger; DO NOT EDIT.

package version_standard

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDownloadProprietaeresFachmodellParams creates a new DownloadProprietaeresFachmodellParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDownloadProprietaeresFachmodellParams() *DownloadProprietaeresFachmodellParams {
	return &DownloadProprietaeresFachmodellParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDownloadProprietaeresFachmodellParamsWithTimeout creates a new DownloadProprietaeresFachmodellParams object
// with the ability to set a timeout on a request.
func NewDownloadProprietaeresFachmodellParamsWithTimeout(timeout time.Duration) *DownloadProprietaeresFachmodellParams {
	return &DownloadProprietaeresFachmodellParams{
		timeout: timeout,
	}
}

// NewDownloadProprietaeresFachmodellParamsWithContext creates a new DownloadProprietaeresFachmodellParams object
// with the ability to set a context for a request.
func NewDownloadProprietaeresFachmodellParamsWithContext(ctx context.Context) *DownloadProprietaeresFachmodellParams {
	return &DownloadProprietaeresFachmodellParams{
		Context: ctx,
	}
}

// NewDownloadProprietaeresFachmodellParamsWithHTTPClient creates a new DownloadProprietaeresFachmodellParams object
// with the ability to set a custom HTTPClient for a request.
func NewDownloadProprietaeresFachmodellParamsWithHTTPClient(client *http.Client) *DownloadProprietaeresFachmodellParams {
	return &DownloadProprietaeresFachmodellParams{
		HTTPClient: client,
	}
}

/*
DownloadProprietaeresFachmodellParams contains all the parameters to send to the API endpoint

	for the download proprietaeres fachmodell operation.

	Typically these are written to a http.Request.
*/
type DownloadProprietaeresFachmodellParams struct {

	// Urn.
	Urn string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the download proprietaeres fachmodell params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DownloadProprietaeresFachmodellParams) WithDefaults() *DownloadProprietaeresFachmodellParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the download proprietaeres fachmodell params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DownloadProprietaeresFachmodellParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the download proprietaeres fachmodell params
func (o *DownloadProprietaeresFachmodellParams) WithTimeout(timeout time.Duration) *DownloadProprietaeresFachmodellParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the download proprietaeres fachmodell params
func (o *DownloadProprietaeresFachmodellParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the download proprietaeres fachmodell params
func (o *DownloadProprietaeresFachmodellParams) WithContext(ctx context.Context) *DownloadProprietaeresFachmodellParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the download proprietaeres fachmodell params
func (o *DownloadProprietaeresFachmodellParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the download proprietaeres fachmodell params
func (o *DownloadProprietaeresFachmodellParams) WithHTTPClient(client *http.Client) *DownloadProprietaeresFachmodellParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the download proprietaeres fachmodell params
func (o *DownloadProprietaeresFachmodellParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUrn adds the urn to the download proprietaeres fachmodell params
func (o *DownloadProprietaeresFachmodellParams) WithUrn(urn string) *DownloadProprietaeresFachmodellParams {
	o.SetUrn(urn)
	return o
}

// SetUrn adds the urn to the download proprietaeres fachmodell params
func (o *DownloadProprietaeresFachmodellParams) SetUrn(urn string) {
	o.Urn = urn
}

// WriteToRequest writes these params to a swagger request
func (o *DownloadProprietaeresFachmodellParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param urn
	if err := r.SetPathParam("urn", o.Urn); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
