// Code generated by go-swagger; DO NOT EDIT.

package version_standard

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DownloadNormalisiertesFachmodellReader is a Reader for the DownloadNormalisiertesFachmodell structure.
type DownloadNormalisiertesFachmodellReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DownloadNormalisiertesFachmodellReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	result := NewDownloadNormalisiertesFachmodellDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result
}

// NewDownloadNormalisiertesFachmodellDefault creates a DownloadNormalisiertesFachmodellDefault with default headers values
func NewDownloadNormalisiertesFachmodellDefault(code int) *DownloadNormalisiertesFachmodellDefault {
	return &DownloadNormalisiertesFachmodellDefault{
		_statusCode: code,
	}
}

/*
DownloadNormalisiertesFachmodellDefault describes a response with status code -1, with default header values.

successful operation
*/
type DownloadNormalisiertesFachmodellDefault struct {
	_statusCode int
}

// IsSuccess returns true when this download normalisiertes fachmodell default response has a 2xx status code
func (o *DownloadNormalisiertesFachmodellDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this download normalisiertes fachmodell default response has a 3xx status code
func (o *DownloadNormalisiertesFachmodellDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this download normalisiertes fachmodell default response has a 4xx status code
func (o *DownloadNormalisiertesFachmodellDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this download normalisiertes fachmodell default response has a 5xx status code
func (o *DownloadNormalisiertesFachmodellDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this download normalisiertes fachmodell default response a status code equal to that given
func (o *DownloadNormalisiertesFachmodellDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the download normalisiertes fachmodell default response
func (o *DownloadNormalisiertesFachmodellDefault) Code() int {
	return o._statusCode
}

func (o *DownloadNormalisiertesFachmodellDefault) Error() string {
	return fmt.Sprintf("[GET /version_standard/{urn}/normalisiertesFachmodellXMI][%d] downloadNormalisiertesFachmodell default ", o._statusCode)
}

func (o *DownloadNormalisiertesFachmodellDefault) String() string {
	return fmt.Sprintf("[GET /version_standard/{urn}/normalisiertesFachmodellXMI][%d] downloadNormalisiertesFachmodell default ", o._statusCode)
}

func (o *DownloadNormalisiertesFachmodellDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
