// Code generated by go-swagger; DO NOT EDIT.

package version_standard

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetModelPlain4Reader is a Reader for the GetModelPlain4 structure.
type GetModelPlain4Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetModelPlain4Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	result := NewGetModelPlain4Default(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result
}

// NewGetModelPlain4Default creates a GetModelPlain4Default with default headers values
func NewGetModelPlain4Default(code int) *GetModelPlain4Default {
	return &GetModelPlain4Default{
		_statusCode: code,
	}
}

/*
GetModelPlain4Default describes a response with status code -1, with default header values.

successful operation
*/
type GetModelPlain4Default struct {
	_statusCode int
}

// IsSuccess returns true when this get model plain 4 default response has a 2xx status code
func (o *GetModelPlain4Default) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get model plain 4 default response has a 3xx status code
func (o *GetModelPlain4Default) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get model plain 4 default response has a 4xx status code
func (o *GetModelPlain4Default) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get model plain 4 default response has a 5xx status code
func (o *GetModelPlain4Default) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get model plain 4 default response a status code equal to that given
func (o *GetModelPlain4Default) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get model plain 4 default response
func (o *GetModelPlain4Default) Code() int {
	return o._statusCode
}

func (o *GetModelPlain4Default) Error() string {
	return fmt.Sprintf("[GET /version_standard/{kennung}][%d] getModelPlain_4 default ", o._statusCode)
}

func (o *GetModelPlain4Default) String() string {
	return fmt.Sprintf("[GET /version_standard/{kennung}][%d] getModelPlain_4 default ", o._statusCode)
}

func (o *GetModelPlain4Default) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
