// Code generated by go-swagger; DO NOT EDIT.

package version_standard

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetBeziehungen4Params creates a new GetBeziehungen4Params object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetBeziehungen4Params() *GetBeziehungen4Params {
	return &GetBeziehungen4Params{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetBeziehungen4ParamsWithTimeout creates a new GetBeziehungen4Params object
// with the ability to set a timeout on a request.
func NewGetBeziehungen4ParamsWithTimeout(timeout time.Duration) *GetBeziehungen4Params {
	return &GetBeziehungen4Params{
		timeout: timeout,
	}
}

// NewGetBeziehungen4ParamsWithContext creates a new GetBeziehungen4Params object
// with the ability to set a context for a request.
func NewGetBeziehungen4ParamsWithContext(ctx context.Context) *GetBeziehungen4Params {
	return &GetBeziehungen4Params{
		Context: ctx,
	}
}

// NewGetBeziehungen4ParamsWithHTTPClient creates a new GetBeziehungen4Params object
// with the ability to set a custom HTTPClient for a request.
func NewGetBeziehungen4ParamsWithHTTPClient(client *http.Client) *GetBeziehungen4Params {
	return &GetBeziehungen4Params{
		HTTPClient: client,
	}
}

/*
GetBeziehungen4Params contains all the parameters to send to the API endpoint

	for the get beziehungen 4 operation.

	Typically these are written to a http.Request.
*/
type GetBeziehungen4Params struct {

	// Urn.
	Urn string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get beziehungen 4 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBeziehungen4Params) WithDefaults() *GetBeziehungen4Params {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get beziehungen 4 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBeziehungen4Params) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get beziehungen 4 params
func (o *GetBeziehungen4Params) WithTimeout(timeout time.Duration) *GetBeziehungen4Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get beziehungen 4 params
func (o *GetBeziehungen4Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get beziehungen 4 params
func (o *GetBeziehungen4Params) WithContext(ctx context.Context) *GetBeziehungen4Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get beziehungen 4 params
func (o *GetBeziehungen4Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get beziehungen 4 params
func (o *GetBeziehungen4Params) WithHTTPClient(client *http.Client) *GetBeziehungen4Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get beziehungen 4 params
func (o *GetBeziehungen4Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUrn adds the urn to the get beziehungen 4 params
func (o *GetBeziehungen4Params) WithUrn(urn string) *GetBeziehungen4Params {
	o.SetUrn(urn)
	return o
}

// SetUrn adds the urn to the get beziehungen 4 params
func (o *GetBeziehungen4Params) SetUrn(urn string) {
	o.Urn = urn
}

// WriteToRequest writes these params to a swagger request
func (o *GetBeziehungen4Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param urn
	if err := r.SetPathParam("urn", o.Urn); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
