// Code generated by go-swagger; DO NOT EDIT.

package version_standard

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetDokumente4Reader is a Reader for the GetDokumente4 structure.
type GetDokumente4Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDokumente4Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	result := NewGetDokumente4Default(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result
}

// NewGetDokumente4Default creates a GetDokumente4Default with default headers values
func NewGetDokumente4Default(code int) *GetDokumente4Default {
	return &GetDokumente4Default{
		_statusCode: code,
	}
}

/*
GetDokumente4Default describes a response with status code -1, with default header values.

successful operation
*/
type GetDokumente4Default struct {
	_statusCode int
}

// IsSuccess returns true when this get dokumente 4 default response has a 2xx status code
func (o *GetDokumente4Default) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get dokumente 4 default response has a 3xx status code
func (o *GetDokumente4Default) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get dokumente 4 default response has a 4xx status code
func (o *GetDokumente4Default) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get dokumente 4 default response has a 5xx status code
func (o *GetDokumente4Default) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get dokumente 4 default response a status code equal to that given
func (o *GetDokumente4Default) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get dokumente 4 default response
func (o *GetDokumente4Default) Code() int {
	return o._statusCode
}

func (o *GetDokumente4Default) Error() string {
	return fmt.Sprintf("[GET /version_standard/{kennung}/dokumente][%d] getDokumente_4 default ", o._statusCode)
}

func (o *GetDokumente4Default) String() string {
	return fmt.Sprintf("[GET /version_standard/{kennung}/dokumente][%d] getDokumente_4 default ", o._statusCode)
}

func (o *GetDokumente4Default) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
