// Code generated by go-swagger; DO NOT EDIT.

package version_standard

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// ZertifizierungsInformationenReader is a Reader for the ZertifizierungsInformationen structure.
type ZertifizierungsInformationenReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ZertifizierungsInformationenReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	result := NewZertifizierungsInformationenDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result
}

// NewZertifizierungsInformationenDefault creates a ZertifizierungsInformationenDefault with default headers values
func NewZertifizierungsInformationenDefault(code int) *ZertifizierungsInformationenDefault {
	return &ZertifizierungsInformationenDefault{
		_statusCode: code,
	}
}

/*
ZertifizierungsInformationenDefault describes a response with status code -1, with default header values.

successful operation
*/
type ZertifizierungsInformationenDefault struct {
	_statusCode int
}

// IsSuccess returns true when this zertifizierungs informationen default response has a 2xx status code
func (o *ZertifizierungsInformationenDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this zertifizierungs informationen default response has a 3xx status code
func (o *ZertifizierungsInformationenDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this zertifizierungs informationen default response has a 4xx status code
func (o *ZertifizierungsInformationenDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this zertifizierungs informationen default response has a 5xx status code
func (o *ZertifizierungsInformationenDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this zertifizierungs informationen default response a status code equal to that given
func (o *ZertifizierungsInformationenDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the zertifizierungs informationen default response
func (o *ZertifizierungsInformationenDefault) Code() int {
	return o._statusCode
}

func (o *ZertifizierungsInformationenDefault) Error() string {
	return fmt.Sprintf("[GET /version_standard/{kennung}/zertifizierung][%d] zertifizierungsInformationen default ", o._statusCode)
}

func (o *ZertifizierungsInformationenDefault) String() string {
	return fmt.Sprintf("[GET /version_standard/{kennung}/zertifizierung][%d] zertifizierungsInformationen default ", o._statusCode)
}

func (o *ZertifizierungsInformationenDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
