// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/diggi-foundation/xrepository/client/administration"
	"github.com/diggi-foundation/xrepository/client/codeliste"
	"github.com/diggi-foundation/xrepository/client/datei"
	"github.com/diggi-foundation/xrepository/client/g_ui"
	"github.com/diggi-foundation/xrepository/client/interop_matrix"
	"github.com/diggi-foundation/xrepository/client/nutzer"
	"github.com/diggi-foundation/xrepository/client/profil"
	"github.com/diggi-foundation/xrepository/client/redaktion"
	"github.com/diggi-foundation/xrepository/client/standard"
	"github.com/diggi-foundation/xrepository/client/version_codeliste"
	"github.com/diggi-foundation/xrepository/client/version_standard"
)

// Default xrepository HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "xrepository.de"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/api"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"http", "https"}

// NewHTTPClient creates a new xrepository HTTP client.
func NewHTTPClient(formats strfmt.Registry) *Xrepository {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new xrepository HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *Xrepository {
	// ensure nullable parameters have default
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new xrepository client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Xrepository {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}

	cli := new(Xrepository)
	cli.Transport = transport
	cli.Administration = administration.New(transport, formats)
	cli.Codeliste = codeliste.New(transport, formats)
	cli.Datei = datei.New(transport, formats)
	cli.GUI = g_ui.New(transport, formats)
	cli.InteropMatrix = interop_matrix.New(transport, formats)
	cli.Nutzer = nutzer.New(transport, formats)
	cli.Profil = profil.New(transport, formats)
	cli.Redaktion = redaktion.New(transport, formats)
	cli.Standard = standard.New(transport, formats)
	cli.VersionCodeliste = version_codeliste.New(transport, formats)
	cli.VersionStandard = version_standard.New(transport, formats)
	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// Xrepository is a client for xrepository
type Xrepository struct {
	Administration administration.ClientService

	Codeliste codeliste.ClientService

	Datei datei.ClientService

	GUI g_ui.ClientService

	InteropMatrix interop_matrix.ClientService

	Nutzer nutzer.ClientService

	Profil profil.ClientService

	Redaktion redaktion.ClientService

	Standard standard.ClientService

	VersionCodeliste version_codeliste.ClientService

	VersionStandard version_standard.ClientService

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *Xrepository) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport
	c.Administration.SetTransport(transport)
	c.Codeliste.SetTransport(transport)
	c.Datei.SetTransport(transport)
	c.GUI.SetTransport(transport)
	c.InteropMatrix.SetTransport(transport)
	c.Nutzer.SetTransport(transport)
	c.Profil.SetTransport(transport)
	c.Redaktion.SetTransport(transport)
	c.Standard.SetTransport(transport)
	c.VersionCodeliste.SetTransport(transport)
	c.VersionStandard.SetTransport(transport)
}
