// Code generated by go-swagger; DO NOT EDIT.

package profil

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// InitResetPasswordReader is a Reader for the InitResetPassword structure.
type InitResetPasswordReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *InitResetPasswordReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	result := NewInitResetPasswordDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result
}

// NewInitResetPasswordDefault creates a InitResetPasswordDefault with default headers values
func NewInitResetPasswordDefault(code int) *InitResetPasswordDefault {
	return &InitResetPasswordDefault{
		_statusCode: code,
	}
}

/*
InitResetPasswordDefault describes a response with status code -1, with default header values.

successful operation
*/
type InitResetPasswordDefault struct {
	_statusCode int
}

// IsSuccess returns true when this init reset password default response has a 2xx status code
func (o *InitResetPasswordDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this init reset password default response has a 3xx status code
func (o *InitResetPasswordDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this init reset password default response has a 4xx status code
func (o *InitResetPasswordDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this init reset password default response has a 5xx status code
func (o *InitResetPasswordDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this init reset password default response a status code equal to that given
func (o *InitResetPasswordDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the init reset password default response
func (o *InitResetPasswordDefault) Code() int {
	return o._statusCode
}

func (o *InitResetPasswordDefault) Error() string {
	return fmt.Sprintf("[POST /profil/passwort_zuruecksetzen][%d] initResetPassword default ", o._statusCode)
}

func (o *InitResetPasswordDefault) String() string {
	return fmt.Sprintf("[POST /profil/passwort_zuruecksetzen][%d] initResetPassword default ", o._statusCode)
}

func (o *InitResetPasswordDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
