// Code generated by go-swagger; DO NOT EDIT.

package profil

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// ResetPasswordReader is a Reader for the ResetPassword structure.
type ResetPasswordReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ResetPasswordReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	result := NewResetPasswordDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result
}

// NewResetPasswordDefault creates a ResetPasswordDefault with default headers values
func NewResetPasswordDefault(code int) *ResetPasswordDefault {
	return &ResetPasswordDefault{
		_statusCode: code,
	}
}

/*
ResetPasswordDefault describes a response with status code -1, with default header values.

successful operation
*/
type ResetPasswordDefault struct {
	_statusCode int
}

// IsSuccess returns true when this reset password default response has a 2xx status code
func (o *ResetPasswordDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this reset password default response has a 3xx status code
func (o *ResetPasswordDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this reset password default response has a 4xx status code
func (o *ResetPasswordDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this reset password default response has a 5xx status code
func (o *ResetPasswordDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this reset password default response a status code equal to that given
func (o *ResetPasswordDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the reset password default response
func (o *ResetPasswordDefault) Code() int {
	return o._statusCode
}

func (o *ResetPasswordDefault) Error() string {
	return fmt.Sprintf("[POST /profil/passwort_zuruecksetzen/{resetKey}][%d] resetPassword default ", o._statusCode)
}

func (o *ResetPasswordDefault) String() string {
	return fmt.Sprintf("[POST /profil/passwort_zuruecksetzen/{resetKey}][%d] resetPassword default ", o._statusCode)
}

func (o *ResetPasswordDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
