// Code generated by go-swagger; DO NOT EDIT.

package datei

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// Abbestellen2Reader is a Reader for the Abbestellen2 structure.
type Abbestellen2Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *Abbestellen2Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	result := NewAbbestellen2Default(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result
}

// NewAbbestellen2Default creates a Abbestellen2Default with default headers values
func NewAbbestellen2Default(code int) *Abbestellen2Default {
	return &Abbestellen2Default{
		_statusCode: code,
	}
}

/*
Abbestellen2Default describes a response with status code -1, with default header values.

successful operation
*/
type Abbestellen2Default struct {
	_statusCode int
}

// IsSuccess returns true when this abbestellen 2 default response has a 2xx status code
func (o *Abbestellen2Default) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this abbestellen 2 default response has a 3xx status code
func (o *Abbestellen2Default) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this abbestellen 2 default response has a 4xx status code
func (o *Abbestellen2Default) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this abbestellen 2 default response has a 5xx status code
func (o *Abbestellen2Default) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this abbestellen 2 default response a status code equal to that given
func (o *Abbestellen2Default) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the abbestellen 2 default response
func (o *Abbestellen2Default) Code() int {
	return o._statusCode
}

func (o *Abbestellen2Default) Error() string {
	return fmt.Sprintf("[POST /datei/{urn}/abbestellen][%d] abbestellen_2 default ", o._statusCode)
}

func (o *Abbestellen2Default) String() string {
	return fmt.Sprintf("[POST /datei/{urn}/abbestellen][%d] abbestellen_2 default ", o._statusCode)
}

func (o *Abbestellen2Default) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
