// Code generated by go-swagger; DO NOT EDIT.

package datei

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetJSON2Params creates a new GetJSON2Params object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetJSON2Params() *GetJSON2Params {
	return &GetJSON2Params{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetJSON2ParamsWithTimeout creates a new GetJSON2Params object
// with the ability to set a timeout on a request.
func NewGetJSON2ParamsWithTimeout(timeout time.Duration) *GetJSON2Params {
	return &GetJSON2Params{
		timeout: timeout,
	}
}

// NewGetJSON2ParamsWithContext creates a new GetJSON2Params object
// with the ability to set a context for a request.
func NewGetJSON2ParamsWithContext(ctx context.Context) *GetJSON2Params {
	return &GetJSON2Params{
		Context: ctx,
	}
}

// NewGetJSON2ParamsWithHTTPClient creates a new GetJSON2Params object
// with the ability to set a custom HTTPClient for a request.
func NewGetJSON2ParamsWithHTTPClient(client *http.Client) *GetJSON2Params {
	return &GetJSON2Params{
		HTTPClient: client,
	}
}

/*
GetJSON2Params contains all the parameters to send to the API endpoint

	for the get Json 2 operation.

	Typically these are written to a http.Request.
*/
type GetJSON2Params struct {

	// Urn.
	Urn string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get Json 2 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetJSON2Params) WithDefaults() *GetJSON2Params {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get Json 2 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetJSON2Params) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get Json 2 params
func (o *GetJSON2Params) WithTimeout(timeout time.Duration) *GetJSON2Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get Json 2 params
func (o *GetJSON2Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get Json 2 params
func (o *GetJSON2Params) WithContext(ctx context.Context) *GetJSON2Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get Json 2 params
func (o *GetJSON2Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get Json 2 params
func (o *GetJSON2Params) WithHTTPClient(client *http.Client) *GetJSON2Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get Json 2 params
func (o *GetJSON2Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUrn adds the urn to the get Json 2 params
func (o *GetJSON2Params) WithUrn(urn string) *GetJSON2Params {
	o.SetUrn(urn)
	return o
}

// SetUrn adds the urn to the get Json 2 params
func (o *GetJSON2Params) SetUrn(urn string) {
	o.Urn = urn
}

// WriteToRequest writes these params to a swagger request
func (o *GetJSON2Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param urn
	if err := r.SetPathParam("urn", o.Urn); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
