// Code generated by go-swagger; DO NOT EDIT.

package version_codeliste

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DownloadGenericodeFachmodellReader is a Reader for the DownloadGenericodeFachmodell structure.
type DownloadGenericodeFachmodellReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DownloadGenericodeFachmodellReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	result := NewDownloadGenericodeFachmodellDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result
}

// NewDownloadGenericodeFachmodellDefault creates a DownloadGenericodeFachmodellDefault with default headers values
func NewDownloadGenericodeFachmodellDefault(code int) *DownloadGenericodeFachmodellDefault {
	return &DownloadGenericodeFachmodellDefault{
		_statusCode: code,
	}
}

/*
DownloadGenericodeFachmodellDefault describes a response with status code -1, with default header values.

successful operation
*/
type DownloadGenericodeFachmodellDefault struct {
	_statusCode int
}

// IsSuccess returns true when this download genericode fachmodell default response has a 2xx status code
func (o *DownloadGenericodeFachmodellDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this download genericode fachmodell default response has a 3xx status code
func (o *DownloadGenericodeFachmodellDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this download genericode fachmodell default response has a 4xx status code
func (o *DownloadGenericodeFachmodellDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this download genericode fachmodell default response has a 5xx status code
func (o *DownloadGenericodeFachmodellDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this download genericode fachmodell default response a status code equal to that given
func (o *DownloadGenericodeFachmodellDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the download genericode fachmodell default response
func (o *DownloadGenericodeFachmodellDefault) Code() int {
	return o._statusCode
}

func (o *DownloadGenericodeFachmodellDefault) Error() string {
	return fmt.Sprintf("[GET /version_codeliste/{kennung}/technischerBestandteilGenericode][%d] downloadGenericodeFachmodell default ", o._statusCode)
}

func (o *DownloadGenericodeFachmodellDefault) String() string {
	return fmt.Sprintf("[GET /version_codeliste/{kennung}/technischerBestandteilGenericode][%d] downloadGenericodeFachmodell default ", o._statusCode)
}

func (o *DownloadGenericodeFachmodellDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
