// Code generated by go-swagger; DO NOT EDIT.

package version_codeliste

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetAsMarkdownReader is a Reader for the GetAsMarkdown structure.
type GetAsMarkdownReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAsMarkdownReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	result := NewGetAsMarkdownDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result
}

// NewGetAsMarkdownDefault creates a GetAsMarkdownDefault with default headers values
func NewGetAsMarkdownDefault(code int) *GetAsMarkdownDefault {
	return &GetAsMarkdownDefault{
		_statusCode: code,
	}
}

/*
GetAsMarkdownDefault describes a response with status code -1, with default header values.

successful operation
*/
type GetAsMarkdownDefault struct {
	_statusCode int
}

// IsSuccess returns true when this get as markdown default response has a 2xx status code
func (o *GetAsMarkdownDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get as markdown default response has a 3xx status code
func (o *GetAsMarkdownDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get as markdown default response has a 4xx status code
func (o *GetAsMarkdownDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get as markdown default response has a 5xx status code
func (o *GetAsMarkdownDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get as markdown default response a status code equal to that given
func (o *GetAsMarkdownDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get as markdown default response
func (o *GetAsMarkdownDefault) Code() int {
	return o._statusCode
}

func (o *GetAsMarkdownDefault) Error() string {
	return fmt.Sprintf("[GET /version_codeliste/{kennung}/download/{name}.md][%d] getAsMarkdown default ", o._statusCode)
}

func (o *GetAsMarkdownDefault) String() string {
	return fmt.Sprintf("[GET /version_codeliste/{kennung}/download/{name}.md][%d] getAsMarkdown default ", o._statusCode)
}

func (o *GetAsMarkdownDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
