// Code generated by go-swagger; DO NOT EDIT.

package version_codeliste

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAsMarkdownParams creates a new GetAsMarkdownParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAsMarkdownParams() *GetAsMarkdownParams {
	return &GetAsMarkdownParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAsMarkdownParamsWithTimeout creates a new GetAsMarkdownParams object
// with the ability to set a timeout on a request.
func NewGetAsMarkdownParamsWithTimeout(timeout time.Duration) *GetAsMarkdownParams {
	return &GetAsMarkdownParams{
		timeout: timeout,
	}
}

// NewGetAsMarkdownParamsWithContext creates a new GetAsMarkdownParams object
// with the ability to set a context for a request.
func NewGetAsMarkdownParamsWithContext(ctx context.Context) *GetAsMarkdownParams {
	return &GetAsMarkdownParams{
		Context: ctx,
	}
}

// NewGetAsMarkdownParamsWithHTTPClient creates a new GetAsMarkdownParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAsMarkdownParamsWithHTTPClient(client *http.Client) *GetAsMarkdownParams {
	return &GetAsMarkdownParams{
		HTTPClient: client,
	}
}

/*
GetAsMarkdownParams contains all the parameters to send to the API endpoint

	for the get as markdown operation.

	Typically these are written to a http.Request.
*/
type GetAsMarkdownParams struct {

	// Kennung.
	Kennung string

	// Name.
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get as markdown params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAsMarkdownParams) WithDefaults() *GetAsMarkdownParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get as markdown params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAsMarkdownParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get as markdown params
func (o *GetAsMarkdownParams) WithTimeout(timeout time.Duration) *GetAsMarkdownParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get as markdown params
func (o *GetAsMarkdownParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get as markdown params
func (o *GetAsMarkdownParams) WithContext(ctx context.Context) *GetAsMarkdownParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get as markdown params
func (o *GetAsMarkdownParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get as markdown params
func (o *GetAsMarkdownParams) WithHTTPClient(client *http.Client) *GetAsMarkdownParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get as markdown params
func (o *GetAsMarkdownParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithKennung adds the kennung to the get as markdown params
func (o *GetAsMarkdownParams) WithKennung(kennung string) *GetAsMarkdownParams {
	o.SetKennung(kennung)
	return o
}

// SetKennung adds the kennung to the get as markdown params
func (o *GetAsMarkdownParams) SetKennung(kennung string) {
	o.Kennung = kennung
}

// WithName adds the name to the get as markdown params
func (o *GetAsMarkdownParams) WithName(name string) *GetAsMarkdownParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get as markdown params
func (o *GetAsMarkdownParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *GetAsMarkdownParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param kennung
	if err := r.SetPathParam("kennung", o.Kennung); err != nil {
		return err
	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
