// Code generated by go-swagger; DO NOT EDIT.

package version_codeliste

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetAsMagicDrawReader is a Reader for the GetAsMagicDraw structure.
type GetAsMagicDrawReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAsMagicDrawReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	result := NewGetAsMagicDrawDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result
}

// NewGetAsMagicDrawDefault creates a GetAsMagicDrawDefault with default headers values
func NewGetAsMagicDrawDefault(code int) *GetAsMagicDrawDefault {
	return &GetAsMagicDrawDefault{
		_statusCode: code,
	}
}

/*
GetAsMagicDrawDefault describes a response with status code -1, with default header values.

successful operation
*/
type GetAsMagicDrawDefault struct {
	_statusCode int
}

// IsSuccess returns true when this get as magic draw default response has a 2xx status code
func (o *GetAsMagicDrawDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get as magic draw default response has a 3xx status code
func (o *GetAsMagicDrawDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get as magic draw default response has a 4xx status code
func (o *GetAsMagicDrawDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get as magic draw default response has a 5xx status code
func (o *GetAsMagicDrawDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get as magic draw default response a status code equal to that given
func (o *GetAsMagicDrawDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get as magic draw default response
func (o *GetAsMagicDrawDefault) Code() int {
	return o._statusCode
}

func (o *GetAsMagicDrawDefault) Error() string {
	return fmt.Sprintf("[GET /version_codeliste/{kennung}/download/{name}.mdxml][%d] getAsMagicDraw default ", o._statusCode)
}

func (o *GetAsMagicDrawDefault) String() string {
	return fmt.Sprintf("[GET /version_codeliste/{kennung}/download/{name}.mdxml][%d] getAsMagicDraw default ", o._statusCode)
}

func (o *GetAsMagicDrawDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
