// Code generated by go-swagger; DO NOT EDIT.

package version_codeliste

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetAsExcelReader is a Reader for the GetAsExcel structure.
type GetAsExcelReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAsExcelReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	result := NewGetAsExcelDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result
}

// NewGetAsExcelDefault creates a GetAsExcelDefault with default headers values
func NewGetAsExcelDefault(code int) *GetAsExcelDefault {
	return &GetAsExcelDefault{
		_statusCode: code,
	}
}

/*
GetAsExcelDefault describes a response with status code -1, with default header values.

successful operation
*/
type GetAsExcelDefault struct {
	_statusCode int
}

// IsSuccess returns true when this get as excel default response has a 2xx status code
func (o *GetAsExcelDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get as excel default response has a 3xx status code
func (o *GetAsExcelDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get as excel default response has a 4xx status code
func (o *GetAsExcelDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get as excel default response has a 5xx status code
func (o *GetAsExcelDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get as excel default response a status code equal to that given
func (o *GetAsExcelDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get as excel default response
func (o *GetAsExcelDefault) Code() int {
	return o._statusCode
}

func (o *GetAsExcelDefault) Error() string {
	return fmt.Sprintf("[GET /version_codeliste/{kennung}/download/{name}.xlsx][%d] getAsExcel default ", o._statusCode)
}

func (o *GetAsExcelDefault) String() string {
	return fmt.Sprintf("[GET /version_codeliste/{kennung}/download/{name}.xlsx][%d] getAsExcel default ", o._statusCode)
}

func (o *GetAsExcelDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
