// Code generated by go-swagger; DO NOT EDIT.

package g_ui

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetNutzerReader is a Reader for the GetNutzer structure.
type GetNutzerReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetNutzerReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	result := NewGetNutzerDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result
}

// NewGetNutzerDefault creates a GetNutzerDefault with default headers values
func NewGetNutzerDefault(code int) *GetNutzerDefault {
	return &GetNutzerDefault{
		_statusCode: code,
	}
}

/*
GetNutzerDefault describes a response with status code -1, with default header values.

successful operation
*/
type GetNutzerDefault struct {
	_statusCode int
}

// IsSuccess returns true when this get nutzer default response has a 2xx status code
func (o *GetNutzerDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get nutzer default response has a 3xx status code
func (o *GetNutzerDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get nutzer default response has a 4xx status code
func (o *GetNutzerDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get nutzer default response has a 5xx status code
func (o *GetNutzerDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get nutzer default response a status code equal to that given
func (o *GetNutzerDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get nutzer default response
func (o *GetNutzerDefault) Code() int {
	return o._statusCode
}

func (o *GetNutzerDefault) Error() string {
	return fmt.Sprintf("[GET /nutzer/{kennung}][%d] getNutzer default ", o._statusCode)
}

func (o *GetNutzerDefault) String() string {
	return fmt.Sprintf("[GET /nutzer/{kennung}][%d] getNutzer default ", o._statusCode)
}

func (o *GetNutzerDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
