// Code generated by go-swagger; DO NOT EDIT.

package g_ui

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewSearchGETParams creates a new SearchGETParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSearchGETParams() *SearchGETParams {
	return &SearchGETParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSearchGETParamsWithTimeout creates a new SearchGETParams object
// with the ability to set a timeout on a request.
func NewSearchGETParamsWithTimeout(timeout time.Duration) *SearchGETParams {
	return &SearchGETParams{
		timeout: timeout,
	}
}

// NewSearchGETParamsWithContext creates a new SearchGETParams object
// with the ability to set a context for a request.
func NewSearchGETParamsWithContext(ctx context.Context) *SearchGETParams {
	return &SearchGETParams{
		Context: ctx,
	}
}

// NewSearchGETParamsWithHTTPClient creates a new SearchGETParams object
// with the ability to set a custom HTTPClient for a request.
func NewSearchGETParamsWithHTTPClient(client *http.Client) *SearchGETParams {
	return &SearchGETParams{
		HTTPClient: client,
	}
}

/*
SearchGETParams contains all the parameters to send to the API endpoint

	for the search g e t operation.

	Typically these are written to a http.Request.
*/
type SearchGETParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the search g e t params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SearchGETParams) WithDefaults() *SearchGETParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the search g e t params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SearchGETParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the search g e t params
func (o *SearchGETParams) WithTimeout(timeout time.Duration) *SearchGETParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the search g e t params
func (o *SearchGETParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the search g e t params
func (o *SearchGETParams) WithContext(ctx context.Context) *SearchGETParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the search g e t params
func (o *SearchGETParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the search g e t params
func (o *SearchGETParams) WithHTTPClient(client *http.Client) *SearchGETParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the search g e t params
func (o *SearchGETParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *SearchGETParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
