// Code generated by go-swagger; DO NOT EDIT.

package g_ui

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// SearchReader is a Reader for the Search structure.
type SearchReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SearchReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	result := NewSearchDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result
}

// NewSearchDefault creates a SearchDefault with default headers values
func NewSearchDefault(code int) *SearchDefault {
	return &SearchDefault{
		_statusCode: code,
	}
}

/*
SearchDefault describes a response with status code -1, with default header values.

successful operation
*/
type SearchDefault struct {
	_statusCode int
}

// IsSuccess returns true when this search default response has a 2xx status code
func (o *SearchDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this search default response has a 3xx status code
func (o *SearchDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this search default response has a 4xx status code
func (o *SearchDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this search default response has a 5xx status code
func (o *SearchDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this search default response a status code equal to that given
func (o *SearchDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the search default response
func (o *SearchDefault) Code() int {
	return o._statusCode
}

func (o *SearchDefault) Error() string {
	return fmt.Sprintf("[POST /nutzer][%d] search default ", o._statusCode)
}

func (o *SearchDefault) String() string {
	return fmt.Sprintf("[POST /nutzer][%d] search default ", o._statusCode)
}

func (o *SearchDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
