// Code generated by go-swagger; DO NOT EDIT.

package g_ui

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/diggi-foundation/xrepository/models"
)

// NewUpdateNutzerParams creates a new UpdateNutzerParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateNutzerParams() *UpdateNutzerParams {
	return &UpdateNutzerParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateNutzerParamsWithTimeout creates a new UpdateNutzerParams object
// with the ability to set a timeout on a request.
func NewUpdateNutzerParamsWithTimeout(timeout time.Duration) *UpdateNutzerParams {
	return &UpdateNutzerParams{
		timeout: timeout,
	}
}

// NewUpdateNutzerParamsWithContext creates a new UpdateNutzerParams object
// with the ability to set a context for a request.
func NewUpdateNutzerParamsWithContext(ctx context.Context) *UpdateNutzerParams {
	return &UpdateNutzerParams{
		Context: ctx,
	}
}

// NewUpdateNutzerParamsWithHTTPClient creates a new UpdateNutzerParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateNutzerParamsWithHTTPClient(client *http.Client) *UpdateNutzerParams {
	return &UpdateNutzerParams{
		HTTPClient: client,
	}
}

/*
UpdateNutzerParams contains all the parameters to send to the API endpoint

	for the update nutzer operation.

	Typically these are written to a http.Request.
*/
type UpdateNutzerParams struct {

	// Body.
	Body *models.NutzerData

	// Kennung.
	Kennung string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update nutzer params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateNutzerParams) WithDefaults() *UpdateNutzerParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update nutzer params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateNutzerParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update nutzer params
func (o *UpdateNutzerParams) WithTimeout(timeout time.Duration) *UpdateNutzerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update nutzer params
func (o *UpdateNutzerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update nutzer params
func (o *UpdateNutzerParams) WithContext(ctx context.Context) *UpdateNutzerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update nutzer params
func (o *UpdateNutzerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update nutzer params
func (o *UpdateNutzerParams) WithHTTPClient(client *http.Client) *UpdateNutzerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update nutzer params
func (o *UpdateNutzerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update nutzer params
func (o *UpdateNutzerParams) WithBody(body *models.NutzerData) *UpdateNutzerParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update nutzer params
func (o *UpdateNutzerParams) SetBody(body *models.NutzerData) {
	o.Body = body
}

// WithKennung adds the kennung to the update nutzer params
func (o *UpdateNutzerParams) WithKennung(kennung string) *UpdateNutzerParams {
	o.SetKennung(kennung)
	return o
}

// SetKennung adds the kennung to the update nutzer params
func (o *UpdateNutzerParams) SetKennung(kennung string) {
	o.Kennung = kennung
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateNutzerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param kennung
	if err := r.SetPathParam("kennung", o.Kennung); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
