// Code generated by go-swagger; DO NOT EDIT.

package redaktion

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewFetch2Params creates a new Fetch2Params object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewFetch2Params() *Fetch2Params {
	return &Fetch2Params{
		timeout: cr.DefaultTimeout,
	}
}

// NewFetch2ParamsWithTimeout creates a new Fetch2Params object
// with the ability to set a timeout on a request.
func NewFetch2ParamsWithTimeout(timeout time.Duration) *Fetch2Params {
	return &Fetch2Params{
		timeout: timeout,
	}
}

// NewFetch2ParamsWithContext creates a new Fetch2Params object
// with the ability to set a context for a request.
func NewFetch2ParamsWithContext(ctx context.Context) *Fetch2Params {
	return &Fetch2Params{
		Context: ctx,
	}
}

// NewFetch2ParamsWithHTTPClient creates a new Fetch2Params object
// with the ability to set a custom HTTPClient for a request.
func NewFetch2ParamsWithHTTPClient(client *http.Client) *Fetch2Params {
	return &Fetch2Params{
		HTTPClient: client,
	}
}

/*
Fetch2Params contains all the parameters to send to the API endpoint

	for the fetch 2 operation.

	Typically these are written to a http.Request.
*/
type Fetch2Params struct {

	// Urn.
	Urn string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the fetch 2 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *Fetch2Params) WithDefaults() *Fetch2Params {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the fetch 2 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *Fetch2Params) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the fetch 2 params
func (o *Fetch2Params) WithTimeout(timeout time.Duration) *Fetch2Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the fetch 2 params
func (o *Fetch2Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the fetch 2 params
func (o *Fetch2Params) WithContext(ctx context.Context) *Fetch2Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the fetch 2 params
func (o *Fetch2Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the fetch 2 params
func (o *Fetch2Params) WithHTTPClient(client *http.Client) *Fetch2Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the fetch 2 params
func (o *Fetch2Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUrn adds the urn to the fetch 2 params
func (o *Fetch2Params) WithUrn(urn string) *Fetch2Params {
	o.SetUrn(urn)
	return o
}

// SetUrn adds the urn to the fetch 2 params
func (o *Fetch2Params) SetUrn(urn string) {
	o.Urn = urn
}

// WriteToRequest writes these params to a swagger request
func (o *Fetch2Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param urn
	if err := r.SetPathParam("urn", o.Urn); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
