// Code generated by go-swagger; DO NOT EDIT.

package redaktion

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewFetchParams creates a new FetchParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewFetchParams() *FetchParams {
	return &FetchParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewFetchParamsWithTimeout creates a new FetchParams object
// with the ability to set a timeout on a request.
func NewFetchParamsWithTimeout(timeout time.Duration) *FetchParams {
	return &FetchParams{
		timeout: timeout,
	}
}

// NewFetchParamsWithContext creates a new FetchParams object
// with the ability to set a context for a request.
func NewFetchParamsWithContext(ctx context.Context) *FetchParams {
	return &FetchParams{
		Context: ctx,
	}
}

// NewFetchParamsWithHTTPClient creates a new FetchParams object
// with the ability to set a custom HTTPClient for a request.
func NewFetchParamsWithHTTPClient(client *http.Client) *FetchParams {
	return &FetchParams{
		HTTPClient: client,
	}
}

/*
FetchParams contains all the parameters to send to the API endpoint

	for the fetch operation.

	Typically these are written to a http.Request.
*/
type FetchParams struct {

	// Urn.
	Urn string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the fetch params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *FetchParams) WithDefaults() *FetchParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the fetch params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *FetchParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the fetch params
func (o *FetchParams) WithTimeout(timeout time.Duration) *FetchParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the fetch params
func (o *FetchParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the fetch params
func (o *FetchParams) WithContext(ctx context.Context) *FetchParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the fetch params
func (o *FetchParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the fetch params
func (o *FetchParams) WithHTTPClient(client *http.Client) *FetchParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the fetch params
func (o *FetchParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUrn adds the urn to the fetch params
func (o *FetchParams) WithUrn(urn string) *FetchParams {
	o.SetUrn(urn)
	return o
}

// SetUrn adds the urn to the fetch params
func (o *FetchParams) SetUrn(urn string) {
	o.Urn = urn
}

// WriteToRequest writes these params to a swagger request
func (o *FetchParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param urn
	if err := r.SetPathParam("urn", o.Urn); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
