// Code generated by go-swagger; DO NOT EDIT.

package redaktion

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// FetchByPathReader is a Reader for the FetchByPath structure.
type FetchByPathReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *FetchByPathReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	result := NewFetchByPathDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result
}

// NewFetchByPathDefault creates a FetchByPathDefault with default headers values
func NewFetchByPathDefault(code int) *FetchByPathDefault {
	return &FetchByPathDefault{
		_statusCode: code,
	}
}

/*
FetchByPathDefault describes a response with status code -1, with default header values.

successful operation
*/
type FetchByPathDefault struct {
	_statusCode int
}

// IsSuccess returns true when this fetch by path default response has a 2xx status code
func (o *FetchByPathDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this fetch by path default response has a 3xx status code
func (o *FetchByPathDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this fetch by path default response has a 4xx status code
func (o *FetchByPathDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this fetch by path default response has a 5xx status code
func (o *FetchByPathDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this fetch by path default response a status code equal to that given
func (o *FetchByPathDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the fetch by path default response
func (o *FetchByPathDefault) Code() int {
	return o._statusCode
}

func (o *FetchByPathDefault) Error() string {
	return fmt.Sprintf("[GET /seite/pfad/{pfad}][%d] fetchByPath default ", o._statusCode)
}

func (o *FetchByPathDefault) String() string {
	return fmt.Sprintf("[GET /seite/pfad/{pfad}][%d] fetchByPath default ", o._statusCode)
}

func (o *FetchByPathDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
