// Code generated by go-swagger; DO NOT EDIT.

package redaktion

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// FetchReader is a Reader for the Fetch structure.
type FetchReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *FetchReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	result := NewFetchDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result
}

// NewFetchDefault creates a FetchDefault with default headers values
func NewFetchDefault(code int) *FetchDefault {
	return &FetchDefault{
		_statusCode: code,
	}
}

/*
FetchDefault describes a response with status code -1, with default header values.

successful operation
*/
type FetchDefault struct {
	_statusCode int
}

// IsSuccess returns true when this fetch default response has a 2xx status code
func (o *FetchDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this fetch default response has a 3xx status code
func (o *FetchDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this fetch default response has a 4xx status code
func (o *FetchDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this fetch default response has a 5xx status code
func (o *FetchDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this fetch default response a status code equal to that given
func (o *FetchDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the fetch default response
func (o *FetchDefault) Code() int {
	return o._statusCode
}

func (o *FetchDefault) Error() string {
	return fmt.Sprintf("[GET /bild/{urn}][%d] fetch default ", o._statusCode)
}

func (o *FetchDefault) String() string {
	return fmt.Sprintf("[GET /bild/{urn}][%d] fetch default ", o._statusCode)
}

func (o *FetchDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
