// Code generated by go-swagger; DO NOT EDIT.

package redaktion

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// FetchAll3Reader is a Reader for the FetchAll3 structure.
type FetchAll3Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *FetchAll3Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	result := NewFetchAll3Default(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result
}

// NewFetchAll3Default creates a FetchAll3Default with default headers values
func NewFetchAll3Default(code int) *FetchAll3Default {
	return &FetchAll3Default{
		_statusCode: code,
	}
}

/*
FetchAll3Default describes a response with status code -1, with default header values.

successful operation
*/
type FetchAll3Default struct {
	_statusCode int
}

// IsSuccess returns true when this fetch all 3 default response has a 2xx status code
func (o *FetchAll3Default) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this fetch all 3 default response has a 3xx status code
func (o *FetchAll3Default) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this fetch all 3 default response has a 4xx status code
func (o *FetchAll3Default) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this fetch all 3 default response has a 5xx status code
func (o *FetchAll3Default) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this fetch all 3 default response a status code equal to that given
func (o *FetchAll3Default) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the fetch all 3 default response
func (o *FetchAll3Default) Code() int {
	return o._statusCode
}

func (o *FetchAll3Default) Error() string {
	return fmt.Sprintf("[GET /seite][%d] fetchAll_3 default ", o._statusCode)
}

func (o *FetchAll3Default) String() string {
	return fmt.Sprintf("[GET /seite][%d] fetchAll_3 default ", o._statusCode)
}

func (o *FetchAll3Default) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
