// Code generated by go-swagger; DO NOT EDIT.

package redaktion

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// Update6Reader is a Reader for the Update6 structure.
type Update6Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *Update6Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	result := NewUpdate6Default(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result
}

// NewUpdate6Default creates a Update6Default with default headers values
func NewUpdate6Default(code int) *Update6Default {
	return &Update6Default{
		_statusCode: code,
	}
}

/*
Update6Default describes a response with status code -1, with default header values.

successful operation
*/
type Update6Default struct {
	_statusCode int
}

// IsSuccess returns true when this update 6 default response has a 2xx status code
func (o *Update6Default) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this update 6 default response has a 3xx status code
func (o *Update6Default) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this update 6 default response has a 4xx status code
func (o *Update6Default) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this update 6 default response has a 5xx status code
func (o *Update6Default) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this update 6 default response a status code equal to that given
func (o *Update6Default) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the update 6 default response
func (o *Update6Default) Code() int {
	return o._statusCode
}

func (o *Update6Default) Error() string {
	return fmt.Sprintf("[POST /seite/{urn}][%d] update_6 default ", o._statusCode)
}

func (o *Update6Default) String() string {
	return fmt.Sprintf("[POST /seite/{urn}][%d] update_6 default ", o._statusCode)
}

func (o *Update6Default) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
