// Code generated by go-swagger; DO NOT EDIT.

package redaktion

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/diggi.foundation/xrepository/models"
)

// NewUpdate5Params creates a new Update5Params object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdate5Params() *Update5Params {
	return &Update5Params{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdate5ParamsWithTimeout creates a new Update5Params object
// with the ability to set a timeout on a request.
func NewUpdate5ParamsWithTimeout(timeout time.Duration) *Update5Params {
	return &Update5Params{
		timeout: timeout,
	}
}

// NewUpdate5ParamsWithContext creates a new Update5Params object
// with the ability to set a context for a request.
func NewUpdate5ParamsWithContext(ctx context.Context) *Update5Params {
	return &Update5Params{
		Context: ctx,
	}
}

// NewUpdate5ParamsWithHTTPClient creates a new Update5Params object
// with the ability to set a custom HTTPClient for a request.
func NewUpdate5ParamsWithHTTPClient(client *http.Client) *Update5Params {
	return &Update5Params{
		HTTPClient: client,
	}
}

/*
Update5Params contains all the parameters to send to the API endpoint

	for the update 5 operation.

	Typically these are written to a http.Request.
*/
type Update5Params struct {

	// Body.
	Body *models.MailTemplate

	// Urn.
	Urn string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update 5 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *Update5Params) WithDefaults() *Update5Params {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update 5 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *Update5Params) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update 5 params
func (o *Update5Params) WithTimeout(timeout time.Duration) *Update5Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update 5 params
func (o *Update5Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update 5 params
func (o *Update5Params) WithContext(ctx context.Context) *Update5Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update 5 params
func (o *Update5Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update 5 params
func (o *Update5Params) WithHTTPClient(client *http.Client) *Update5Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update 5 params
func (o *Update5Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update 5 params
func (o *Update5Params) WithBody(body *models.MailTemplate) *Update5Params {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update 5 params
func (o *Update5Params) SetBody(body *models.MailTemplate) {
	o.Body = body
}

// WithUrn adds the urn to the update 5 params
func (o *Update5Params) WithUrn(urn string) *Update5Params {
	o.SetUrn(urn)
	return o
}

// SetUrn adds the urn to the update 5 params
func (o *Update5Params) SetUrn(urn string) {
	o.Urn = urn
}

// WriteToRequest writes these params to a swagger request
func (o *Update5Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param urn
	if err := r.SetPathParam("urn", o.Urn); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
