// Code generated by go-swagger; DO NOT EDIT.

package redaktion

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// UploadReader is a Reader for the Upload structure.
type UploadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UploadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	result := NewUploadDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result
}

// NewUploadDefault creates a UploadDefault with default headers values
func NewUploadDefault(code int) *UploadDefault {
	return &UploadDefault{
		_statusCode: code,
	}
}

/*
UploadDefault describes a response with status code -1, with default header values.

successful operation
*/
type UploadDefault struct {
	_statusCode int
}

// IsSuccess returns true when this upload default response has a 2xx status code
func (o *UploadDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this upload default response has a 3xx status code
func (o *UploadDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this upload default response has a 4xx status code
func (o *UploadDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this upload default response has a 5xx status code
func (o *UploadDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this upload default response a status code equal to that given
func (o *UploadDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the upload default response
func (o *UploadDefault) Code() int {
	return o._statusCode
}

func (o *UploadDefault) Error() string {
	return fmt.Sprintf("[POST /seite][%d] upload default ", o._statusCode)
}

func (o *UploadDefault) String() string {
	return fmt.Sprintf("[POST /seite][%d] upload default ", o._statusCode)
}

func (o *UploadDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
