// Code generated by go-swagger; DO NOT EDIT.

package x_ö_v_bibliothek

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewXoevFreigebenParams creates a new XoevFreigebenParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewXoevFreigebenParams() *XoevFreigebenParams {
	return &XoevFreigebenParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewXoevFreigebenParamsWithTimeout creates a new XoevFreigebenParams object
// with the ability to set a timeout on a request.
func NewXoevFreigebenParamsWithTimeout(timeout time.Duration) *XoevFreigebenParams {
	return &XoevFreigebenParams{
		timeout: timeout,
	}
}

// NewXoevFreigebenParamsWithContext creates a new XoevFreigebenParams object
// with the ability to set a context for a request.
func NewXoevFreigebenParamsWithContext(ctx context.Context) *XoevFreigebenParams {
	return &XoevFreigebenParams{
		Context: ctx,
	}
}

// NewXoevFreigebenParamsWithHTTPClient creates a new XoevFreigebenParams object
// with the ability to set a custom HTTPClient for a request.
func NewXoevFreigebenParamsWithHTTPClient(client *http.Client) *XoevFreigebenParams {
	return &XoevFreigebenParams{
		HTTPClient: client,
	}
}

/*
XoevFreigebenParams contains all the parameters to send to the API endpoint

	for the xoev freigeben operation.

	Typically these are written to a http.Request.
*/
type XoevFreigebenParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the xoev freigeben params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *XoevFreigebenParams) WithDefaults() *XoevFreigebenParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the xoev freigeben params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *XoevFreigebenParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the xoev freigeben params
func (o *XoevFreigebenParams) WithTimeout(timeout time.Duration) *XoevFreigebenParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the xoev freigeben params
func (o *XoevFreigebenParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the xoev freigeben params
func (o *XoevFreigebenParams) WithContext(ctx context.Context) *XoevFreigebenParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the xoev freigeben params
func (o *XoevFreigebenParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the xoev freigeben params
func (o *XoevFreigebenParams) WithHTTPClient(client *http.Client) *XoevFreigebenParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the xoev freigeben params
func (o *XoevFreigebenParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *XoevFreigebenParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
