// Code generated by go-swagger; DO NOT EDIT.

package x_ö_v_bibliothek

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// XoevFreigebenReader is a Reader for the XoevFreigeben structure.
type XoevFreigebenReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *XoevFreigebenReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	result := NewXoevFreigebenDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result
}

// NewXoevFreigebenDefault creates a XoevFreigebenDefault with default headers values
func NewXoevFreigebenDefault(code int) *XoevFreigebenDefault {
	return &XoevFreigebenDefault{
		_statusCode: code,
	}
}

/*
XoevFreigebenDefault describes a response with status code -1, with default header values.

successful operation
*/
type XoevFreigebenDefault struct {
	_statusCode int
}

// IsSuccess returns true when this xoev freigeben default response has a 2xx status code
func (o *XoevFreigebenDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this xoev freigeben default response has a 3xx status code
func (o *XoevFreigebenDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this xoev freigeben default response has a 4xx status code
func (o *XoevFreigebenDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this xoev freigeben default response has a 5xx status code
func (o *XoevFreigebenDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this xoev freigeben default response a status code equal to that given
func (o *XoevFreigebenDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the xoev freigeben default response
func (o *XoevFreigebenDefault) Code() int {
	return o._statusCode
}

func (o *XoevFreigebenDefault) Error() string {
	return fmt.Sprintf("[POST /xoev_bibliothek/freigeben][%d] xoevFreigeben default ", o._statusCode)
}

func (o *XoevFreigebenDefault) String() string {
	return fmt.Sprintf("[POST /xoev_bibliothek/freigeben][%d] xoevFreigeben default ", o._statusCode)
}

func (o *XoevFreigebenDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
