// Code generated by go-swagger; DO NOT EDIT.

package interop_matrix

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetInteropDatenParams creates a new GetInteropDatenParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetInteropDatenParams() *GetInteropDatenParams {
	return &GetInteropDatenParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetInteropDatenParamsWithTimeout creates a new GetInteropDatenParams object
// with the ability to set a timeout on a request.
func NewGetInteropDatenParamsWithTimeout(timeout time.Duration) *GetInteropDatenParams {
	return &GetInteropDatenParams{
		timeout: timeout,
	}
}

// NewGetInteropDatenParamsWithContext creates a new GetInteropDatenParams object
// with the ability to set a context for a request.
func NewGetInteropDatenParamsWithContext(ctx context.Context) *GetInteropDatenParams {
	return &GetInteropDatenParams{
		Context: ctx,
	}
}

// NewGetInteropDatenParamsWithHTTPClient creates a new GetInteropDatenParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetInteropDatenParamsWithHTTPClient(client *http.Client) *GetInteropDatenParams {
	return &GetInteropDatenParams{
		HTTPClient: client,
	}
}

/*
GetInteropDatenParams contains all the parameters to send to the API endpoint

	for the get interop daten operation.

	Typically these are written to a http.Request.
*/
type GetInteropDatenParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get interop daten params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetInteropDatenParams) WithDefaults() *GetInteropDatenParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get interop daten params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetInteropDatenParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get interop daten params
func (o *GetInteropDatenParams) WithTimeout(timeout time.Duration) *GetInteropDatenParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get interop daten params
func (o *GetInteropDatenParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get interop daten params
func (o *GetInteropDatenParams) WithContext(ctx context.Context) *GetInteropDatenParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get interop daten params
func (o *GetInteropDatenParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get interop daten params
func (o *GetInteropDatenParams) WithHTTPClient(client *http.Client) *GetInteropDatenParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get interop daten params
func (o *GetInteropDatenParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetInteropDatenParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
