// Code generated by go-swagger; DO NOT EDIT.

package administration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetValidierungsBerichtReader is a Reader for the GetValidierungsBericht structure.
type GetValidierungsBerichtReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetValidierungsBerichtReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	result := NewGetValidierungsBerichtDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result
}

// NewGetValidierungsBerichtDefault creates a GetValidierungsBerichtDefault with default headers values
func NewGetValidierungsBerichtDefault(code int) *GetValidierungsBerichtDefault {
	return &GetValidierungsBerichtDefault{
		_statusCode: code,
	}
}

/*
GetValidierungsBerichtDefault describes a response with status code -1, with default header values.

successful operation
*/
type GetValidierungsBerichtDefault struct {
	_statusCode int
}

// IsSuccess returns true when this get validierungs bericht default response has a 2xx status code
func (o *GetValidierungsBerichtDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get validierungs bericht default response has a 3xx status code
func (o *GetValidierungsBerichtDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get validierungs bericht default response has a 4xx status code
func (o *GetValidierungsBerichtDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get validierungs bericht default response has a 5xx status code
func (o *GetValidierungsBerichtDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get validierungs bericht default response a status code equal to that given
func (o *GetValidierungsBerichtDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get validierungs bericht default response
func (o *GetValidierungsBerichtDefault) Code() int {
	return o._statusCode
}

func (o *GetValidierungsBerichtDefault) Error() string {
	return fmt.Sprintf("[GET /administration/validation/report.xml][%d] getValidierungsBericht default ", o._statusCode)
}

func (o *GetValidierungsBerichtDefault) String() string {
	return fmt.Sprintf("[GET /administration/validation/report.xml][%d] getValidierungsBericht default ", o._statusCode)
}

func (o *GetValidierungsBerichtDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
