// Code generated by go-swagger; DO NOT EDIT.

package administration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetValidierungsBerichtParams creates a new GetValidierungsBerichtParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetValidierungsBerichtParams() *GetValidierungsBerichtParams {
	return &GetValidierungsBerichtParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetValidierungsBerichtParamsWithTimeout creates a new GetValidierungsBerichtParams object
// with the ability to set a timeout on a request.
func NewGetValidierungsBerichtParamsWithTimeout(timeout time.Duration) *GetValidierungsBerichtParams {
	return &GetValidierungsBerichtParams{
		timeout: timeout,
	}
}

// NewGetValidierungsBerichtParamsWithContext creates a new GetValidierungsBerichtParams object
// with the ability to set a context for a request.
func NewGetValidierungsBerichtParamsWithContext(ctx context.Context) *GetValidierungsBerichtParams {
	return &GetValidierungsBerichtParams{
		Context: ctx,
	}
}

// NewGetValidierungsBerichtParamsWithHTTPClient creates a new GetValidierungsBerichtParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetValidierungsBerichtParamsWithHTTPClient(client *http.Client) *GetValidierungsBerichtParams {
	return &GetValidierungsBerichtParams{
		HTTPClient: client,
	}
}

/*
GetValidierungsBerichtParams contains all the parameters to send to the API endpoint

	for the get validierungs bericht operation.

	Typically these are written to a http.Request.
*/
type GetValidierungsBerichtParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get validierungs bericht params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetValidierungsBerichtParams) WithDefaults() *GetValidierungsBerichtParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get validierungs bericht params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetValidierungsBerichtParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get validierungs bericht params
func (o *GetValidierungsBerichtParams) WithTimeout(timeout time.Duration) *GetValidierungsBerichtParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get validierungs bericht params
func (o *GetValidierungsBerichtParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get validierungs bericht params
func (o *GetValidierungsBerichtParams) WithContext(ctx context.Context) *GetValidierungsBerichtParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get validierungs bericht params
func (o *GetValidierungsBerichtParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get validierungs bericht params
func (o *GetValidierungsBerichtParams) WithHTTPClient(client *http.Client) *GetValidierungsBerichtParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get validierungs bericht params
func (o *GetValidierungsBerichtParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetValidierungsBerichtParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
