// Code generated by go-swagger; DO NOT EDIT.

package administration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewStarteValidationParams creates a new StarteValidationParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewStarteValidationParams() *StarteValidationParams {
	return &StarteValidationParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewStarteValidationParamsWithTimeout creates a new StarteValidationParams object
// with the ability to set a timeout on a request.
func NewStarteValidationParamsWithTimeout(timeout time.Duration) *StarteValidationParams {
	return &StarteValidationParams{
		timeout: timeout,
	}
}

// NewStarteValidationParamsWithContext creates a new StarteValidationParams object
// with the ability to set a context for a request.
func NewStarteValidationParamsWithContext(ctx context.Context) *StarteValidationParams {
	return &StarteValidationParams{
		Context: ctx,
	}
}

// NewStarteValidationParamsWithHTTPClient creates a new StarteValidationParams object
// with the ability to set a custom HTTPClient for a request.
func NewStarteValidationParamsWithHTTPClient(client *http.Client) *StarteValidationParams {
	return &StarteValidationParams{
		HTTPClient: client,
	}
}

/*
StarteValidationParams contains all the parameters to send to the API endpoint

	for the starte validation operation.

	Typically these are written to a http.Request.
*/
type StarteValidationParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the starte validation params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *StarteValidationParams) WithDefaults() *StarteValidationParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the starte validation params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *StarteValidationParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the starte validation params
func (o *StarteValidationParams) WithTimeout(timeout time.Duration) *StarteValidationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the starte validation params
func (o *StarteValidationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the starte validation params
func (o *StarteValidationParams) WithContext(ctx context.Context) *StarteValidationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the starte validation params
func (o *StarteValidationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the starte validation params
func (o *StarteValidationParams) WithHTTPClient(client *http.Client) *StarteValidationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the starte validation params
func (o *StarteValidationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *StarteValidationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
