// Code generated by go-swagger; DO NOT EDIT.

package codeliste

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetAllGenericodeParams creates a new GetAllGenericodeParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAllGenericodeParams() *GetAllGenericodeParams {
	return &GetAllGenericodeParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAllGenericodeParamsWithTimeout creates a new GetAllGenericodeParams object
// with the ability to set a timeout on a request.
func NewGetAllGenericodeParamsWithTimeout(timeout time.Duration) *GetAllGenericodeParams {
	return &GetAllGenericodeParams{
		timeout: timeout,
	}
}

// NewGetAllGenericodeParamsWithContext creates a new GetAllGenericodeParams object
// with the ability to set a context for a request.
func NewGetAllGenericodeParamsWithContext(ctx context.Context) *GetAllGenericodeParams {
	return &GetAllGenericodeParams{
		Context: ctx,
	}
}

// NewGetAllGenericodeParamsWithHTTPClient creates a new GetAllGenericodeParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAllGenericodeParamsWithHTTPClient(client *http.Client) *GetAllGenericodeParams {
	return &GetAllGenericodeParams{
		HTTPClient: client,
	}
}

/*
GetAllGenericodeParams contains all the parameters to send to the API endpoint

	for the get all genericode operation.

	Typically these are written to a http.Request.
*/
type GetAllGenericodeParams struct {

	// Kennung.
	Kennung string

	// Limit.
	//
	// Format: int32
	Limit *int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get all genericode params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAllGenericodeParams) WithDefaults() *GetAllGenericodeParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get all genericode params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAllGenericodeParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get all genericode params
func (o *GetAllGenericodeParams) WithTimeout(timeout time.Duration) *GetAllGenericodeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get all genericode params
func (o *GetAllGenericodeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get all genericode params
func (o *GetAllGenericodeParams) WithContext(ctx context.Context) *GetAllGenericodeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get all genericode params
func (o *GetAllGenericodeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get all genericode params
func (o *GetAllGenericodeParams) WithHTTPClient(client *http.Client) *GetAllGenericodeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get all genericode params
func (o *GetAllGenericodeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithKennung adds the kennung to the get all genericode params
func (o *GetAllGenericodeParams) WithKennung(kennung string) *GetAllGenericodeParams {
	o.SetKennung(kennung)
	return o
}

// SetKennung adds the kennung to the get all genericode params
func (o *GetAllGenericodeParams) SetKennung(kennung string) {
	o.Kennung = kennung
}

// WithLimit adds the limit to the get all genericode params
func (o *GetAllGenericodeParams) WithLimit(limit *int32) *GetAllGenericodeParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get all genericode params
func (o *GetAllGenericodeParams) SetLimit(limit *int32) {
	o.Limit = limit
}

// WriteToRequest writes these params to a swagger request
func (o *GetAllGenericodeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param kennung
	if err := r.SetPathParam("kennung", o.Kennung); err != nil {
		return err
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int32

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt32(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
