// Code generated by go-swagger; DO NOT EDIT.

package codeliste

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetBeziehungenParams creates a new GetBeziehungenParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetBeziehungenParams() *GetBeziehungenParams {
	return &GetBeziehungenParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetBeziehungenParamsWithTimeout creates a new GetBeziehungenParams object
// with the ability to set a timeout on a request.
func NewGetBeziehungenParamsWithTimeout(timeout time.Duration) *GetBeziehungenParams {
	return &GetBeziehungenParams{
		timeout: timeout,
	}
}

// NewGetBeziehungenParamsWithContext creates a new GetBeziehungenParams object
// with the ability to set a context for a request.
func NewGetBeziehungenParamsWithContext(ctx context.Context) *GetBeziehungenParams {
	return &GetBeziehungenParams{
		Context: ctx,
	}
}

// NewGetBeziehungenParamsWithHTTPClient creates a new GetBeziehungenParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetBeziehungenParamsWithHTTPClient(client *http.Client) *GetBeziehungenParams {
	return &GetBeziehungenParams{
		HTTPClient: client,
	}
}

/*
GetBeziehungenParams contains all the parameters to send to the API endpoint

	for the get beziehungen operation.

	Typically these are written to a http.Request.
*/
type GetBeziehungenParams struct {

	// Urn.
	Urn string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get beziehungen params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBeziehungenParams) WithDefaults() *GetBeziehungenParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get beziehungen params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBeziehungenParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get beziehungen params
func (o *GetBeziehungenParams) WithTimeout(timeout time.Duration) *GetBeziehungenParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get beziehungen params
func (o *GetBeziehungenParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get beziehungen params
func (o *GetBeziehungenParams) WithContext(ctx context.Context) *GetBeziehungenParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get beziehungen params
func (o *GetBeziehungenParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get beziehungen params
func (o *GetBeziehungenParams) WithHTTPClient(client *http.Client) *GetBeziehungenParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get beziehungen params
func (o *GetBeziehungenParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUrn adds the urn to the get beziehungen params
func (o *GetBeziehungenParams) WithUrn(urn string) *GetBeziehungenParams {
	o.SetUrn(urn)
	return o
}

// SetUrn adds the urn to the get beziehungen params
func (o *GetBeziehungenParams) SetUrn(urn string) {
	o.Urn = urn
}

// WriteToRequest writes these params to a swagger request
func (o *GetBeziehungenParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param urn
	if err := r.SetPathParam("urn", o.Urn); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
