// Code generated by go-swagger; DO NOT EDIT.

package codeliste

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetJSONReader is a Reader for the GetJSON structure.
type GetJSONReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetJSONReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	result := NewGetJSONDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result
}

// NewGetJSONDefault creates a GetJSONDefault with default headers values
func NewGetJSONDefault(code int) *GetJSONDefault {
	return &GetJSONDefault{
		_statusCode: code,
	}
}

/*
GetJSONDefault describes a response with status code -1, with default header values.

successful operation
*/
type GetJSONDefault struct {
	_statusCode int
}

// IsSuccess returns true when this get Json default response has a 2xx status code
func (o *GetJSONDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get Json default response has a 3xx status code
func (o *GetJSONDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get Json default response has a 4xx status code
func (o *GetJSONDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get Json default response has a 5xx status code
func (o *GetJSONDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get Json default response a status code equal to that given
func (o *GetJSONDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get Json default response
func (o *GetJSONDefault) Code() int {
	return o._statusCode
}

func (o *GetJSONDefault) Error() string {
	return fmt.Sprintf("[GET /codeliste/{urn}/model][%d] getJson default ", o._statusCode)
}

func (o *GetJSONDefault) String() string {
	return fmt.Sprintf("[GET /codeliste/{urn}/model][%d] getJson default ", o._statusCode)
}

func (o *GetJSONDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
