// Code generated by go-swagger; DO NOT EDIT.

package codeliste

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/diggi-foundation/xrepository/models"
)

// GetDebugInfoReader is a Reader for the GetDebugInfo structure.
type GetDebugInfoReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDebugInfoReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetDebugInfoOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /codeliste/{urn}/debugInfo] getDebugInfo", response, response.Code())
	}
}

// NewGetDebugInfoOK creates a GetDebugInfoOK with default headers values
func NewGetDebugInfoOK() *GetDebugInfoOK {
	return &GetDebugInfoOK{}
}

/*
GetDebugInfoOK describes a response with status code 200, with default header values.

successful operation
*/
type GetDebugInfoOK struct {
	Payload *models.DebugInfo
}

// IsSuccess returns true when this get debug info o k response has a 2xx status code
func (o *GetDebugInfoOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get debug info o k response has a 3xx status code
func (o *GetDebugInfoOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get debug info o k response has a 4xx status code
func (o *GetDebugInfoOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get debug info o k response has a 5xx status code
func (o *GetDebugInfoOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get debug info o k response a status code equal to that given
func (o *GetDebugInfoOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get debug info o k response
func (o *GetDebugInfoOK) Code() int {
	return 200
}

func (o *GetDebugInfoOK) Error() string {
	return fmt.Sprintf("[GET /codeliste/{urn}/debugInfo][%d] getDebugInfoOK  %+v", 200, o.Payload)
}

func (o *GetDebugInfoOK) String() string {
	return fmt.Sprintf("[GET /codeliste/{urn}/debugInfo][%d] getDebugInfoOK  %+v", 200, o.Payload)
}

func (o *GetDebugInfoOK) GetPayload() *models.DebugInfo {
	return o.Payload
}

func (o *GetDebugInfoOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DebugInfo)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
