// Code generated by go-swagger; DO NOT EDIT.

package codeliste

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetAnfrageTokenReader is a Reader for the GetAnfrageToken structure.
type GetAnfrageTokenReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAnfrageTokenReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	result := NewGetAnfrageTokenDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result
}

// NewGetAnfrageTokenDefault creates a GetAnfrageTokenDefault with default headers values
func NewGetAnfrageTokenDefault(code int) *GetAnfrageTokenDefault {
	return &GetAnfrageTokenDefault{
		_statusCode: code,
	}
}

/*
GetAnfrageTokenDefault describes a response with status code -1, with default header values.

successful operation
*/
type GetAnfrageTokenDefault struct {
	_statusCode int
}

// IsSuccess returns true when this get anfrage token default response has a 2xx status code
func (o *GetAnfrageTokenDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get anfrage token default response has a 3xx status code
func (o *GetAnfrageTokenDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get anfrage token default response has a 4xx status code
func (o *GetAnfrageTokenDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get anfrage token default response has a 5xx status code
func (o *GetAnfrageTokenDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get anfrage token default response a status code equal to that given
func (o *GetAnfrageTokenDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get anfrage token default response
func (o *GetAnfrageTokenDefault) Code() int {
	return o._statusCode
}

func (o *GetAnfrageTokenDefault) Error() string {
	return fmt.Sprintf("[GET /codeliste/{kennung}/anfrage/token][%d] getAnfrageToken default ", o._statusCode)
}

func (o *GetAnfrageTokenDefault) String() string {
	return fmt.Sprintf("[GET /codeliste/{kennung}/anfrage/token][%d] getAnfrageToken default ", o._statusCode)
}

func (o *GetAnfrageTokenDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
