// Code generated by go-swagger; DO NOT EDIT.

package codeliste

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetJSONParams creates a new GetJSONParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetJSONParams() *GetJSONParams {
	return &GetJSONParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetJSONParamsWithTimeout creates a new GetJSONParams object
// with the ability to set a timeout on a request.
func NewGetJSONParamsWithTimeout(timeout time.Duration) *GetJSONParams {
	return &GetJSONParams{
		timeout: timeout,
	}
}

// NewGetJSONParamsWithContext creates a new GetJSONParams object
// with the ability to set a context for a request.
func NewGetJSONParamsWithContext(ctx context.Context) *GetJSONParams {
	return &GetJSONParams{
		Context: ctx,
	}
}

// NewGetJSONParamsWithHTTPClient creates a new GetJSONParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetJSONParamsWithHTTPClient(client *http.Client) *GetJSONParams {
	return &GetJSONParams{
		HTTPClient: client,
	}
}

/*
GetJSONParams contains all the parameters to send to the API endpoint

	for the get Json operation.

	Typically these are written to a http.Request.
*/
type GetJSONParams struct {

	// Urn.
	Urn string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get Json params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetJSONParams) WithDefaults() *GetJSONParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get Json params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetJSONParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get Json params
func (o *GetJSONParams) WithTimeout(timeout time.Duration) *GetJSONParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get Json params
func (o *GetJSONParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get Json params
func (o *GetJSONParams) WithContext(ctx context.Context) *GetJSONParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get Json params
func (o *GetJSONParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get Json params
func (o *GetJSONParams) WithHTTPClient(client *http.Client) *GetJSONParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get Json params
func (o *GetJSONParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUrn adds the urn to the get Json params
func (o *GetJSONParams) WithUrn(urn string) *GetJSONParams {
	o.SetUrn(urn)
	return o
}

// SetUrn adds the urn to the get Json params
func (o *GetJSONParams) SetUrn(urn string) {
	o.Urn = urn
}

// WriteToRequest writes these params to a swagger request
func (o *GetJSONParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param urn
	if err := r.SetPathParam("urn", o.Urn); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
