// Code generated by go-swagger; DO NOT EDIT.

package codeliste

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetModelPlainParams creates a new GetModelPlainParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetModelPlainParams() *GetModelPlainParams {
	return &GetModelPlainParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetModelPlainParamsWithTimeout creates a new GetModelPlainParams object
// with the ability to set a timeout on a request.
func NewGetModelPlainParamsWithTimeout(timeout time.Duration) *GetModelPlainParams {
	return &GetModelPlainParams{
		timeout: timeout,
	}
}

// NewGetModelPlainParamsWithContext creates a new GetModelPlainParams object
// with the ability to set a context for a request.
func NewGetModelPlainParamsWithContext(ctx context.Context) *GetModelPlainParams {
	return &GetModelPlainParams{
		Context: ctx,
	}
}

// NewGetModelPlainParamsWithHTTPClient creates a new GetModelPlainParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetModelPlainParamsWithHTTPClient(client *http.Client) *GetModelPlainParams {
	return &GetModelPlainParams{
		HTTPClient: client,
	}
}

/*
GetModelPlainParams contains all the parameters to send to the API endpoint

	for the get model plain operation.

	Typically these are written to a http.Request.
*/
type GetModelPlainParams struct {

	// Kennung.
	Kennung string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get model plain params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetModelPlainParams) WithDefaults() *GetModelPlainParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get model plain params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetModelPlainParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get model plain params
func (o *GetModelPlainParams) WithTimeout(timeout time.Duration) *GetModelPlainParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get model plain params
func (o *GetModelPlainParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get model plain params
func (o *GetModelPlainParams) WithContext(ctx context.Context) *GetModelPlainParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get model plain params
func (o *GetModelPlainParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get model plain params
func (o *GetModelPlainParams) WithHTTPClient(client *http.Client) *GetModelPlainParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get model plain params
func (o *GetModelPlainParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithKennung adds the kennung to the get model plain params
func (o *GetModelPlainParams) WithKennung(kennung string) *GetModelPlainParams {
	o.SetKennung(kennung)
	return o
}

// SetKennung adds the kennung to the get model plain params
func (o *GetModelPlainParams) SetKennung(kennung string) {
	o.Kennung = kennung
}

// WriteToRequest writes these params to a swagger request
func (o *GetModelPlainParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param kennung
	if err := r.SetPathParam("kennung", o.Kennung); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
