// Code generated by go-swagger; DO NOT EDIT.

package codeliste

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewMetadatenParams creates a new MetadatenParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewMetadatenParams() *MetadatenParams {
	return &MetadatenParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewMetadatenParamsWithTimeout creates a new MetadatenParams object
// with the ability to set a timeout on a request.
func NewMetadatenParamsWithTimeout(timeout time.Duration) *MetadatenParams {
	return &MetadatenParams{
		timeout: timeout,
	}
}

// NewMetadatenParamsWithContext creates a new MetadatenParams object
// with the ability to set a context for a request.
func NewMetadatenParamsWithContext(ctx context.Context) *MetadatenParams {
	return &MetadatenParams{
		Context: ctx,
	}
}

// NewMetadatenParamsWithHTTPClient creates a new MetadatenParams object
// with the ability to set a custom HTTPClient for a request.
func NewMetadatenParamsWithHTTPClient(client *http.Client) *MetadatenParams {
	return &MetadatenParams{
		HTTPClient: client,
	}
}

/*
MetadatenParams contains all the parameters to send to the API endpoint

	for the metadaten operation.

	Typically these are written to a http.Request.
*/
type MetadatenParams struct {

	// Urn.
	Urn string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the metadaten params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MetadatenParams) WithDefaults() *MetadatenParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the metadaten params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MetadatenParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the metadaten params
func (o *MetadatenParams) WithTimeout(timeout time.Duration) *MetadatenParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the metadaten params
func (o *MetadatenParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the metadaten params
func (o *MetadatenParams) WithContext(ctx context.Context) *MetadatenParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the metadaten params
func (o *MetadatenParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the metadaten params
func (o *MetadatenParams) WithHTTPClient(client *http.Client) *MetadatenParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the metadaten params
func (o *MetadatenParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUrn adds the urn to the metadaten params
func (o *MetadatenParams) WithUrn(urn string) *MetadatenParams {
	o.SetUrn(urn)
	return o
}

// SetUrn adds the urn to the metadaten params
func (o *MetadatenParams) SetUrn(urn string) {
	o.Urn = urn
}

// WriteToRequest writes these params to a swagger request
func (o *MetadatenParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param urn
	if err := r.SetPathParam("urn", o.Urn); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
