// Code generated by go-swagger; DO NOT EDIT.

package codeliste

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// RemoveTechnischerBestandteilReader is a Reader for the RemoveTechnischerBestandteil structure.
type RemoveTechnischerBestandteilReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RemoveTechnischerBestandteilReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	result := NewRemoveTechnischerBestandteilDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result
}

// NewRemoveTechnischerBestandteilDefault creates a RemoveTechnischerBestandteilDefault with default headers values
func NewRemoveTechnischerBestandteilDefault(code int) *RemoveTechnischerBestandteilDefault {
	return &RemoveTechnischerBestandteilDefault{
		_statusCode: code,
	}
}

/*
RemoveTechnischerBestandteilDefault describes a response with status code -1, with default header values.

successful operation
*/
type RemoveTechnischerBestandteilDefault struct {
	_statusCode int
}

// IsSuccess returns true when this remove technischer bestandteil default response has a 2xx status code
func (o *RemoveTechnischerBestandteilDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this remove technischer bestandteil default response has a 3xx status code
func (o *RemoveTechnischerBestandteilDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this remove technischer bestandteil default response has a 4xx status code
func (o *RemoveTechnischerBestandteilDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this remove technischer bestandteil default response has a 5xx status code
func (o *RemoveTechnischerBestandteilDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this remove technischer bestandteil default response a status code equal to that given
func (o *RemoveTechnischerBestandteilDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the remove technischer bestandteil default response
func (o *RemoveTechnischerBestandteilDefault) Code() int {
	return o._statusCode
}

func (o *RemoveTechnischerBestandteilDefault) Error() string {
	return fmt.Sprintf("[DELETE /codeliste/{urn}/technischerBestandteil/{name}][%d] removeTechnischerBestandteil default ", o._statusCode)
}

func (o *RemoveTechnischerBestandteilDefault) String() string {
	return fmt.Sprintf("[DELETE /codeliste/{urn}/technischerBestandteil/{name}][%d] removeTechnischerBestandteil default ", o._statusCode)
}

func (o *RemoveTechnischerBestandteilDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
