// Code generated by go-swagger; DO NOT EDIT.

package codeliste

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// SendAnfrageReader is a Reader for the SendAnfrage structure.
type SendAnfrageReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SendAnfrageReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	result := NewSendAnfrageDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result
}

// NewSendAnfrageDefault creates a SendAnfrageDefault with default headers values
func NewSendAnfrageDefault(code int) *SendAnfrageDefault {
	return &SendAnfrageDefault{
		_statusCode: code,
	}
}

/*
SendAnfrageDefault describes a response with status code -1, with default header values.

successful operation
*/
type SendAnfrageDefault struct {
	_statusCode int
}

// IsSuccess returns true when this send anfrage default response has a 2xx status code
func (o *SendAnfrageDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this send anfrage default response has a 3xx status code
func (o *SendAnfrageDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this send anfrage default response has a 4xx status code
func (o *SendAnfrageDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this send anfrage default response has a 5xx status code
func (o *SendAnfrageDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this send anfrage default response a status code equal to that given
func (o *SendAnfrageDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the send anfrage default response
func (o *SendAnfrageDefault) Code() int {
	return o._statusCode
}

func (o *SendAnfrageDefault) Error() string {
	return fmt.Sprintf("[POST /codeliste/{kennung}/anfrage][%d] sendAnfrage default ", o._statusCode)
}

func (o *SendAnfrageDefault) String() string {
	return fmt.Sprintf("[POST /codeliste/{kennung}/anfrage][%d] sendAnfrage default ", o._statusCode)
}

func (o *SendAnfrageDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
