// Code generated by go-swagger; DO NOT EDIT.

package codeliste

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// TransferOwnershipReader is a Reader for the TransferOwnership structure.
type TransferOwnershipReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TransferOwnershipReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	result := NewTransferOwnershipDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result
}

// NewTransferOwnershipDefault creates a TransferOwnershipDefault with default headers values
func NewTransferOwnershipDefault(code int) *TransferOwnershipDefault {
	return &TransferOwnershipDefault{
		_statusCode: code,
	}
}

/*
TransferOwnershipDefault describes a response with status code -1, with default header values.

successful operation
*/
type TransferOwnershipDefault struct {
	_statusCode int
}

// IsSuccess returns true when this transfer ownership default response has a 2xx status code
func (o *TransferOwnershipDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this transfer ownership default response has a 3xx status code
func (o *TransferOwnershipDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this transfer ownership default response has a 4xx status code
func (o *TransferOwnershipDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this transfer ownership default response has a 5xx status code
func (o *TransferOwnershipDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this transfer ownership default response a status code equal to that given
func (o *TransferOwnershipDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the transfer ownership default response
func (o *TransferOwnershipDefault) Code() int {
	return o._statusCode
}

func (o *TransferOwnershipDefault) Error() string {
	return fmt.Sprintf("[POST /codeliste/{urn}/transfer-owner][%d] transferOwnership default ", o._statusCode)
}

func (o *TransferOwnershipDefault) String() string {
	return fmt.Sprintf("[POST /codeliste/{urn}/transfer-owner][%d] transferOwnership default ", o._statusCode)
}

func (o *TransferOwnershipDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
