// Code generated by go-swagger; DO NOT EDIT.

package standard

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetTechnischerBestandteil1Params creates a new GetTechnischerBestandteil1Params object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetTechnischerBestandteil1Params() *GetTechnischerBestandteil1Params {
	return &GetTechnischerBestandteil1Params{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetTechnischerBestandteil1ParamsWithTimeout creates a new GetTechnischerBestandteil1Params object
// with the ability to set a timeout on a request.
func NewGetTechnischerBestandteil1ParamsWithTimeout(timeout time.Duration) *GetTechnischerBestandteil1Params {
	return &GetTechnischerBestandteil1Params{
		timeout: timeout,
	}
}

// NewGetTechnischerBestandteil1ParamsWithContext creates a new GetTechnischerBestandteil1Params object
// with the ability to set a context for a request.
func NewGetTechnischerBestandteil1ParamsWithContext(ctx context.Context) *GetTechnischerBestandteil1Params {
	return &GetTechnischerBestandteil1Params{
		Context: ctx,
	}
}

// NewGetTechnischerBestandteil1ParamsWithHTTPClient creates a new GetTechnischerBestandteil1Params object
// with the ability to set a custom HTTPClient for a request.
func NewGetTechnischerBestandteil1ParamsWithHTTPClient(client *http.Client) *GetTechnischerBestandteil1Params {
	return &GetTechnischerBestandteil1Params{
		HTTPClient: client,
	}
}

/*
GetTechnischerBestandteil1Params contains all the parameters to send to the API endpoint

	for the get technischer bestandteil 1 operation.

	Typically these are written to a http.Request.
*/
type GetTechnischerBestandteil1Params struct {

	// Kennung.
	Kennung string

	// Name.
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get technischer bestandteil 1 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetTechnischerBestandteil1Params) WithDefaults() *GetTechnischerBestandteil1Params {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get technischer bestandteil 1 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetTechnischerBestandteil1Params) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get technischer bestandteil 1 params
func (o *GetTechnischerBestandteil1Params) WithTimeout(timeout time.Duration) *GetTechnischerBestandteil1Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get technischer bestandteil 1 params
func (o *GetTechnischerBestandteil1Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get technischer bestandteil 1 params
func (o *GetTechnischerBestandteil1Params) WithContext(ctx context.Context) *GetTechnischerBestandteil1Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get technischer bestandteil 1 params
func (o *GetTechnischerBestandteil1Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get technischer bestandteil 1 params
func (o *GetTechnischerBestandteil1Params) WithHTTPClient(client *http.Client) *GetTechnischerBestandteil1Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get technischer bestandteil 1 params
func (o *GetTechnischerBestandteil1Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithKennung adds the kennung to the get technischer bestandteil 1 params
func (o *GetTechnischerBestandteil1Params) WithKennung(kennung string) *GetTechnischerBestandteil1Params {
	o.SetKennung(kennung)
	return o
}

// SetKennung adds the kennung to the get technischer bestandteil 1 params
func (o *GetTechnischerBestandteil1Params) SetKennung(kennung string) {
	o.Kennung = kennung
}

// WithName adds the name to the get technischer bestandteil 1 params
func (o *GetTechnischerBestandteil1Params) WithName(name string) *GetTechnischerBestandteil1Params {
	o.SetName(name)
	return o
}

// SetName adds the name to the get technischer bestandteil 1 params
func (o *GetTechnischerBestandteil1Params) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *GetTechnischerBestandteil1Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param kennung
	if err := r.SetPathParam("kennung", o.Kennung); err != nil {
		return err
	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
