// Code generated by go-swagger; DO NOT EDIT.

package standard

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/diggi.foundation/xrepository/models"
)

// GetDebugInfo3Reader is a Reader for the GetDebugInfo3 structure.
type GetDebugInfo3Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDebugInfo3Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetDebugInfo3OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /standard/{urn}/debugInfo] getDebugInfo_3", response, response.Code())
	}
}

// NewGetDebugInfo3OK creates a GetDebugInfo3OK with default headers values
func NewGetDebugInfo3OK() *GetDebugInfo3OK {
	return &GetDebugInfo3OK{}
}

/*
GetDebugInfo3OK describes a response with status code 200, with default header values.

successful operation
*/
type GetDebugInfo3OK struct {
	Payload *models.DebugInfo
}

// IsSuccess returns true when this get debug info3 o k response has a 2xx status code
func (o *GetDebugInfo3OK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get debug info3 o k response has a 3xx status code
func (o *GetDebugInfo3OK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get debug info3 o k response has a 4xx status code
func (o *GetDebugInfo3OK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get debug info3 o k response has a 5xx status code
func (o *GetDebugInfo3OK) IsServerError() bool {
	return false
}

// IsCode returns true when this get debug info3 o k response a status code equal to that given
func (o *GetDebugInfo3OK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get debug info3 o k response
func (o *GetDebugInfo3OK) Code() int {
	return 200
}

func (o *GetDebugInfo3OK) Error() string {
	return fmt.Sprintf("[GET /standard/{urn}/debugInfo][%d] getDebugInfo3OK  %+v", 200, o.Payload)
}

func (o *GetDebugInfo3OK) String() string {
	return fmt.Sprintf("[GET /standard/{urn}/debugInfo][%d] getDebugInfo3OK  %+v", 200, o.Payload)
}

func (o *GetDebugInfo3OK) GetPayload() *models.DebugInfo {
	return o.Payload
}

func (o *GetDebugInfo3OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DebugInfo)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
