// Code generated by go-swagger; DO NOT EDIT.

package standard

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAnfrageToken1Params creates a new GetAnfrageToken1Params object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAnfrageToken1Params() *GetAnfrageToken1Params {
	return &GetAnfrageToken1Params{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAnfrageToken1ParamsWithTimeout creates a new GetAnfrageToken1Params object
// with the ability to set a timeout on a request.
func NewGetAnfrageToken1ParamsWithTimeout(timeout time.Duration) *GetAnfrageToken1Params {
	return &GetAnfrageToken1Params{
		timeout: timeout,
	}
}

// NewGetAnfrageToken1ParamsWithContext creates a new GetAnfrageToken1Params object
// with the ability to set a context for a request.
func NewGetAnfrageToken1ParamsWithContext(ctx context.Context) *GetAnfrageToken1Params {
	return &GetAnfrageToken1Params{
		Context: ctx,
	}
}

// NewGetAnfrageToken1ParamsWithHTTPClient creates a new GetAnfrageToken1Params object
// with the ability to set a custom HTTPClient for a request.
func NewGetAnfrageToken1ParamsWithHTTPClient(client *http.Client) *GetAnfrageToken1Params {
	return &GetAnfrageToken1Params{
		HTTPClient: client,
	}
}

/*
GetAnfrageToken1Params contains all the parameters to send to the API endpoint

	for the get anfrage token 1 operation.

	Typically these are written to a http.Request.
*/
type GetAnfrageToken1Params struct {

	// Kennung.
	Kennung string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get anfrage token 1 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAnfrageToken1Params) WithDefaults() *GetAnfrageToken1Params {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get anfrage token 1 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAnfrageToken1Params) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get anfrage token 1 params
func (o *GetAnfrageToken1Params) WithTimeout(timeout time.Duration) *GetAnfrageToken1Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get anfrage token 1 params
func (o *GetAnfrageToken1Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get anfrage token 1 params
func (o *GetAnfrageToken1Params) WithContext(ctx context.Context) *GetAnfrageToken1Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get anfrage token 1 params
func (o *GetAnfrageToken1Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get anfrage token 1 params
func (o *GetAnfrageToken1Params) WithHTTPClient(client *http.Client) *GetAnfrageToken1Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get anfrage token 1 params
func (o *GetAnfrageToken1Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithKennung adds the kennung to the get anfrage token 1 params
func (o *GetAnfrageToken1Params) WithKennung(kennung string) *GetAnfrageToken1Params {
	o.SetKennung(kennung)
	return o
}

// SetKennung adds the kennung to the get anfrage token 1 params
func (o *GetAnfrageToken1Params) SetKennung(kennung string) {
	o.Kennung = kennung
}

// WriteToRequest writes these params to a swagger request
func (o *GetAnfrageToken1Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param kennung
	if err := r.SetPathParam("kennung", o.Kennung); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
