// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Anfrage anfrage
//
// swagger:model Anfrage
type Anfrage struct {

	// absender email
	AbsenderEmail string `json:"absenderEmail,omitempty"`

	// absender name
	AbsenderName string `json:"absenderName,omitempty"`

	// anfrage text
	AnfrageText string `json:"anfrageText,omitempty"`

	// ansprechpartner index
	// Required: true
	AnsprechpartnerIndex *int32 `json:"ansprechpartnerIndex"`

	// send copy to sender
	SendCopyToSender bool `json:"sendCopyToSender,omitempty"`

	// token
	Token string `json:"token,omitempty"`
}

// Validate validates this anfrage
func (m *Anfrage) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAnsprechpartnerIndex(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Anfrage) validateAnsprechpartnerIndex(formats strfmt.Registry) error {

	if err := validate.Required("ansprechpartnerIndex", "body", m.AnsprechpartnerIndex); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this anfrage based on context it is used
func (m *Anfrage) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Anfrage) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Anfrage) UnmarshalBinary(b []byte) error {
	var res Anfrage
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
