// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AnsprechpartnerData ansprechpartner data
//
// swagger:model AnsprechpartnerData
type AnsprechpartnerData struct {

	// email
	Email string `json:"email,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// organisation
	Organisation string `json:"organisation,omitempty"`

	// vorname
	Vorname string `json:"vorname,omitempty"`
}

// Validate validates this ansprechpartner data
func (m *AnsprechpartnerData) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this ansprechpartner data based on context it is used
func (m *AnsprechpartnerData) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AnsprechpartnerData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AnsprechpartnerData) UnmarshalBinary(b []byte) error {
	var res AnsprechpartnerData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
