// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CodeStatusZertifizierung code status zertifizierung
//
// swagger:model CodeStatusZertifizierung
type CodeStatusZertifizierung struct {

	// code
	// Required: true
	// Enum: [NICHT_ZERTIFIZIERT ZERTIFIZIERT ZERTIFIZIERUNG_BEANTRAGT]
	Code *string `json:"code" xml:"code"`
}

// Validate validates this code status zertifizierung
func (m *CodeStatusZertifizierung) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCode(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var codeStatusZertifizierungTypeCodePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["NICHT_ZERTIFIZIERT","ZERTIFIZIERT","ZERTIFIZIERUNG_BEANTRAGT"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		codeStatusZertifizierungTypeCodePropEnum = append(codeStatusZertifizierungTypeCodePropEnum, v)
	}
}

const (

	// CodeStatusZertifizierungCodeNICHTZERTIFIZIERT captures enum value "NICHT_ZERTIFIZIERT"
	CodeStatusZertifizierungCodeNICHTZERTIFIZIERT string = "NICHT_ZERTIFIZIERT"

	// CodeStatusZertifizierungCodeZERTIFIZIERT captures enum value "ZERTIFIZIERT"
	CodeStatusZertifizierungCodeZERTIFIZIERT string = "ZERTIFIZIERT"

	// CodeStatusZertifizierungCodeZERTIFIZIERUNGBEANTRAGT captures enum value "ZERTIFIZIERUNG_BEANTRAGT"
	CodeStatusZertifizierungCodeZERTIFIZIERUNGBEANTRAGT string = "ZERTIFIZIERUNG_BEANTRAGT"
)

// prop value enum
func (m *CodeStatusZertifizierung) validateCodeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, codeStatusZertifizierungTypeCodePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *CodeStatusZertifizierung) validateCode(formats strfmt.Registry) error {

	if err := validate.Required("code", "body", m.Code); err != nil {
		return err
	}

	// value enum
	if err := m.validateCodeEnum("code", "body", *m.Code); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this code status zertifizierung based on context it is used
func (m *CodeStatusZertifizierung) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CodeStatusZertifizierung) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CodeStatusZertifizierung) UnmarshalBinary(b []byte) error {
	var res CodeStatusZertifizierung
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
