// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GenericodeDaten genericode daten
//
// swagger:model GenericodeDaten
type GenericodeDaten struct {

	// daten
	Daten [][]string `json:"daten"`

	// metadaten
	Metadaten *Metadaten `json:"metadaten,omitempty"`

	// spalten
	Spalten []*SpalteExtrakt `json:"spalten"`
}

// Validate validates this genericode daten
func (m *GenericodeDaten) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMetadaten(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSpalten(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GenericodeDaten) validateMetadaten(formats strfmt.Registry) error {
	if swag.IsZero(m.Metadaten) { // not required
		return nil
	}

	if m.Metadaten != nil {
		if err := m.Metadaten.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("metadaten")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("metadaten")
			}
			return err
		}
	}

	return nil
}

func (m *GenericodeDaten) validateSpalten(formats strfmt.Registry) error {
	if swag.IsZero(m.Spalten) { // not required
		return nil
	}

	for i := 0; i < len(m.Spalten); i++ {
		if swag.IsZero(m.Spalten[i]) { // not required
			continue
		}

		if m.Spalten[i] != nil {
			if err := m.Spalten[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("spalten" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("spalten" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this genericode daten based on the context it is used
func (m *GenericodeDaten) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateMetadaten(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateSpalten(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GenericodeDaten) contextValidateMetadaten(ctx context.Context, formats strfmt.Registry) error {

	if m.Metadaten != nil {

		if swag.IsZero(m.Metadaten) { // not required
			return nil
		}

		if err := m.Metadaten.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("metadaten")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("metadaten")
			}
			return err
		}
	}

	return nil
}

func (m *GenericodeDaten) contextValidateSpalten(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Spalten); i++ {

		if m.Spalten[i] != nil {

			if swag.IsZero(m.Spalten[i]) { // not required
				return nil
			}

			if err := m.Spalten[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("spalten" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("spalten" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *GenericodeDaten) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GenericodeDaten) UnmarshalBinary(b []byte) error {
	var res GenericodeDaten
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
