// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// KomplexerBasistypExtrakt komplexer basistyp extrakt
//
// swagger:model KomplexerBasistypExtrakt
type KomplexerBasistypExtrakt struct {

	// art der ableitung
	ArtDerAbleitung string `json:"artDerAbleitung,omitempty" xml:"artDerAbleitung,omitempty"`

	// typ kennung
	TypKennung string `json:"typKennung,omitempty" xml:"typ.kennung,omitempty"`

	// typ name
	// Required: true
	TypName *string `json:"typName" xml:"typ.name"`
}

// Validate validates this komplexer basistyp extrakt
func (m *KomplexerBasistypExtrakt) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTypName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *KomplexerBasistypExtrakt) validateTypName(formats strfmt.Registry) error {

	if err := validate.Required("typName", "body", m.TypName); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this komplexer basistyp extrakt based on context it is used
func (m *KomplexerBasistypExtrakt) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *KomplexerBasistypExtrakt) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *KomplexerBasistypExtrakt) UnmarshalBinary(b []byte) error {
	var res KomplexerBasistypExtrakt
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
