// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TransferInhaltInfo transfer inhalt info
//
// swagger:model TransferInhaltInfo
type TransferInhaltInfo struct {

	// current owner
	CurrentOwner string `json:"currentOwner,omitempty"`

	// inhalte
	Inhalte []string `json:"inhalte"`

	// new owner
	NewOwner string `json:"newOwner,omitempty"`
}

// Validate validates this transfer inhalt info
func (m *TransferInhaltInfo) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this transfer inhalt info based on context it is used
func (m *TransferInhaltInfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TransferInhaltInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TransferInhaltInfo) UnmarshalBinary(b []byte) error {
	var res TransferInhaltInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
