// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// XmlschemaExtrakt xmlschema extrakt
//
// swagger:model XmlschemaExtrakt
type XmlschemaExtrakt struct {

	// datei
	// Required: true
	Datei []*XmlschemaDateiExtrakt `json:"datei" xml:"datei"`
}

// Validate validates this xmlschema extrakt
func (m *XmlschemaExtrakt) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDatei(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *XmlschemaExtrakt) validateDatei(formats strfmt.Registry) error {

	if err := validate.Required("datei", "body", m.Datei); err != nil {
		return err
	}

	for i := 0; i < len(m.Datei); i++ {
		if swag.IsZero(m.Datei[i]) { // not required
			continue
		}

		if m.Datei[i] != nil {
			if err := m.Datei[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("datei" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("datei" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this xmlschema extrakt based on the context it is used
func (m *XmlschemaExtrakt) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateDatei(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *XmlschemaExtrakt) contextValidateDatei(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Datei); i++ {

		if m.Datei[i] != nil {

			if swag.IsZero(m.Datei[i]) { // not required
				return nil
			}

			if err := m.Datei[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("datei" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("datei" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *XmlschemaExtrakt) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *XmlschemaExtrakt) UnmarshalBinary(b []byte) error {
	var res XmlschemaExtrakt
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
